apiVersion: v1
appVersion: 10-0076
description: Micro Focus Postgres Database
keywords:
- database
- postgres
maintainers:
- email: robert.balser@microfocus.com
  name: robert
name: postgres
version: 1.0.94
