global:
  nom:
    edition: 

  docker:
    # set the global.docker.registry and orgName to your internal Docker registry/org
    registry: docker.registry.net
    orgName: hpeswitom
    imagePullSecret: "regcred"
    imagePullPolicy: IfNotPresent

  # persistence.enabled=true means that the PVCs are expected to be dynamically created by the composition chart.
  # Otherwise, persistence.dataVolumeClaim is a persistent volume claim for storing data files.
  # persistence.logVolumeClaim is a persistent volume claim for storing log files.
  # If all of the above are undefined, then temporary ephemeral storage will be created (only if isDemo=true)
  persistence:
    enabled: false
    dataVolumeClaim:
    logVolumeClaim:

  # Set the default time to live for Jobs after finishing
  jobs:
    ttlSecondsAfterFinished: 1209600

  database:
    internal: true # default is embedded

  opsbridgeIntegration:
    isSelected: false

  #Properties for Shared Optic Reporting
  services:
    sharedOpticReporting: false
    namespace:
    external:
      host:
      port:
    internal:
      host:
      port:

  # User ID and group ID to run as
  securityContext:
    user: "1999"
    fsGroup: "1999"
    
  rbac:
    # Specifies whether a ServiceAccount should be created
    serviceAccountCreate: true  

  # Global image definitions
  vaultRenew:
    image: kubernetes-vault-renew
    imageTag: 0.8.0-006
  vaultInit:
    image: kubernetes-vault-init
    imageTag: 0.8.0-006
  busybox:
    image: itom-busybox
    imageTag: ${image.busybox.version}
  opensuse:
    image: opensuse-base
    imageTag: 15.2-0074

deployment:
  # by default upload the AutoPass PD file, but composition chart can disable
  uploadAutoPassLicense: true
  idm:
    # IDM now has a name prefix, which can be changed by composition chart.
    namePrefix: "itom-"
    service: idm-svc
    port: 18443
    user: nomadmin
    passwordKey: idm_nom_admin_password

  replicas: 2

#####################
# Image definitions
#####################
nomConfig:
  image: itom-nom-config
  imageTag: 2.2.73
