{{- if .Values.didataaccess.config.isNodePortEnabled }}
kind: Service
apiVersion: v1
metadata:
  labels:
    app.kubernetes.io/name: itom-di-data-access-svc
    app.kubernetes.io/managed-by: {{.Release.Name}}
    app.kubernetes.io/version: {{.Values.dataAccess.imageTag}}
    itom.microfocus.com/capability: itom-data-ingestion
    tier.itom.microfocus.com/backend: backend
  name: itom-di-data-access-svc
  annotations:
    {{ template "dataaccess.service_domain" . }}
    {{- if eq .Values.global.cluster.k8sProvider "aws" }}
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    {{- else if eq .Values.global.cluster.k8sProvider "azure" }}
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    {{- end }}
spec:
  type: {{ template "dataaccess.service_type" . }}
  {{ template "dataaccess.azure_loadbalancer_ip" . }}
  {{ template "dataaccess.cloud_loadbalancer_source_range" . }}
  ports:
  {{- if (eq (include  "dataaccess.is_cloud_deployment" . ) "false") }}
  - name: data-access-port-old
    port: 8443
    protocol: TCP
    targetPort: 8443
  {{- end }}
  - name: data-access-port
    port: 28443
    targetPort: 8443
  selector:
    app: itom-di-data-access
{{end}}
