{{- if and .Values.didataaccess.config.isNodePortEnabled (eq (include  "dataaccess.is_cloud_deployment" . ) "false") }}
kind: Service
apiVersion: v1
metadata:
  name: data-access-nodeport
spec:
  type: NodePort
  ports:
    - port: 28443
      targetPort: 8443
      nodePort: {{.Values.didataaccess.config.accessNodePort}}
  selector:
    app: itom-di-data-access
{{end}}