global:
  docker:
    # set the global.docker.registry and orgName to your internal Docker registry/org
    registry: docker.registry.net
    orgName: hpeswitom
    imagePullSecret: "regcred"
    imagePullPolicy: IfNotPresent

  # persistence.dataVolumeClaim is a persistent volume claim for storing NNMi data files.
  # persistence.logVolume is a persistent volume claim for storing NNMi log files.
  # persistence.configVolume is a persistent volume claim for storing NNMi configuration files.
  # If any of these is undefined, then temporary ephemeral storage will be created.
  persistence:
    enabled: false
    dataVolumeClaim:
    logVolumeClaim:


  securityContext:
    user: "1999"
    fsGroup: "1999"

  rbac:
    # Specifies whether a ServiceAccount should be created
    serviceAccountCreate: true

  tlsTruststore:

  #Properties for Shared Optic Reporting
  services:
    sharedOpticReporting: false
    namespace:
    external:
      host:
      port:
    internal:
      host:
      port:

  # global image references
  vaultRenew:
    image: kubernetes-vault-renew
    imageTag: 0.9.0-006
  vaultInit:
    image: kubernetes-vault-init
    imageTag: 0.9.0-006
  busybox:
    image: itom-busybox
    imageTag: ${image.itom-busybox.version}
  opensuse:
    image: opensuse-base
    imageTag: 15.2-0074

  coso:
    isSelected: true
  perfTroubleshooting:
    isSelected: false

  nginx:
    annotationPrefix:

  # Set the time to live for Jobs after finishing
  jobs:
    ttlSecondsAfterFinished: 1209600

# Assigning pods to cluster nodes
nodeSelector:
  Worker: label

tolerations: []

affinity: {}

deployment:
  idm:
    # IDM now has a name prefix, which can be changed by composition chart.
    namePrefix: "itom-"
    service: idm-svc
    port: 18443
  bvdExplore:
    service: "bvd-explore"
    port: 4000
  replicas: 3

adminUser: "nomadmin"
adminUserPasswordKey: idm_nom_admin_password

perfTroubleshooting:
  datasource: coso,nps

#####################
# Image definitions
#####################
nomUi:
  image: itom-nom-ui
  imageTag: 3.4.77
