{{ $namePrefix := include "namePrefix" . }}
{{- if .Values.global.rbac.serviceAccountCreate }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $namePrefix }}-cdf-reloader
imagePullSecrets:
- name: {{ .Values.global.docker.imagePullSecret | default "registrypullsecret" }}
{{- end }}
---
{{- if .Values.global.rbac.roleCreate }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $namePrefix }}:reloader
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - ""
    resources:
      {{- if .Values.reloader.ignoreSecrets }}
      {{- else }}
      - secrets
      {{- end }}
      {{- if .Values.reloader.ignoreConfigMaps }}
      {{- else }}
      - configmaps
      {{- end }}
    verbs:
      - list
      - get
      - watch
  {{- if or (.Capabilities.APIVersions.Has "apps.openshift.io/v1") (eq .Values.global.k8sProvider "openshift") }}
  - apiGroups:
      - "apps.openshift.io"
      - ""
    resources:
      - deploymentconfigs
    verbs:
      - list
      - get
      - update
      - patch
  {{- end }}
  - apiGroups:
      - "apps"
    resources:
      - deployments
      - daemonsets
      - statefulsets
    verbs:
      - list
      - get
      - update
      - patch
  - apiGroups:
      - "extensions"
    resources:
      - deployments
      - daemonsets
    verbs:
      - list
      - get
      - update
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $namePrefix }}-reloader-role-binding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $namePrefix }}:reloader
subjects:
  - kind: ServiceAccount
    name: {{ $namePrefix }}-cdf-reloader
    namespace: {{ .Release.Namespace }}
{{- end }}
