{{- if .Values.divertica.config.isNodePortEnabled}}
kind: Service
apiVersion: v1
metadata:
  name: itom-di-vertica-nodeport
spec:
  type: NodePort
  ports:
  - port: 5433
    protocol: TCP
    name: itom-di-vertica-nodeport
    nodePort: {{.Values.divertica.config.verticaNodePort}}
    targetPort: 5433
  selector:
    name: itom-di-vertica-pod
{{end}}
