{{- if .Values.global.rbac.serviceAccountCreate }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.deployment.rbac.serviceAccount | default "itom-di-vertica-sa" }}
  namespace: {{ .Release.Namespace }}
imagePullSecrets:
- name: {{ .Values.global.docker.imagePullSecret | default "registrypullsecret" }}
{{- end }}
---
{{- if .Values.global.rbac.roleCreate }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "itomdi:vertica"
rules:
- apiGroups: [""]
  resources:  
   - configmaps
   - serviceaccounts
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
   - pods  
  verbs: ["list", "get", "update", "create", "delete", "patch"]   
- apiGroups: [""]
  resources:  
   - services
   - secrets
  verbs: ["list", "watch", "get", "update", "create", "delete", "patch"]   
- apiGroups: ["apps"]
  resources:
   - deployments    
   - statefulsets
   - replicasets
   - deployments
  verbs: ["list", "watch", "get", "update", "create", "delete", "patch"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "itomdi:vertica"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "itomdi:vertica"
subjects:
- kind: ServiceAccount 
  name: {{ .Values.deployment.rbac.serviceAccount | default "itom-di-vertica-sa" }}
  namespace: {{ .Release.Namespace }}
{{- end }}