{{- if .Values.diminio.pdb }}
{{- if .Values.diminio.pdb.usePolicy }}
{{- if .Capabilities.APIVersions.Has "policy/v1" -}}
apiVersion: policy/v1
{{- else }}
apiVersion: policy/v1beta1
{{- end }}
kind: PodDisruptionBudget
metadata:
  name: {{ template "minio.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "minio.name" . }}
spec:
  selector:
    matchLabels:
      app: {{ template "minio.name" . }}
  maxUnavailable: {{ .Values.diminio.pdb.maxUnavailable }}
{{- end }}
{{- end }}
