apiVersion: v1
kind: Service
metadata:
  name: itom-di-configuration-svc
spec:
  ports:
  - name: configuration-port
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app: itom-di-administration