apiVersion: v1
kind: Service
metadata:
  name: bvd-ap-bridge
  namespace: {{ .Release.Namespace }}
  labels:
    service: bvd-ap-bridge
    app.kubernetes.io/name: bvd-ap-bridge
    app.kubernetes.io/managed-by: bvd-config
    app.kubernetes.io/version: {{ .Values.bvd.imageTag }}
    itom.microfocus.com/capability: bvd  
    tier.itom.microfocus.com/autopassService: autopassService 
spec:
  ports:
  - name: bvd-ap-bridge
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    service: bvd-ap-bridge
