# Config information of services that BVD/UIS is dependent on
apiVersion: v1
kind: ConfigMap
metadata:
  name: bvd-services-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: bvd
    app.kubernetes.io/name: bvd-services-config
    app.kubernetes.io/managed-by: bvd-services-config
    app.kubernetes.io/version: {{ .Values.bvd.imageTag }}
    itom.microfocus.com/capability: bvd
    tier.itom.microfocus.com/config: config
data:
  suite.namespace: {{ .Release.Namespace }}
  suite.vault_addr: https://itom-vault:8200
  suite.autopasslicenseserver: https://{{ (coalesce (include "helm-lib.getAplsHost" .) "itom-autopass-lms") }}:{{ (coalesce (include "helm-lib.getAplsPort" .) 5814) }}
  suite.integration_user: {{ .Values.global.idm.integrationUser | default "integration_admin" | quote }}
  suite.integration_user_password_key: {{ .Values.global.idm.integrationUserKey | default "idm_integration_admin_password" | quote }}
  suite.idm_transport_key: {{ .Values.global.idm.transportUserKey | default "idm_transport_admin_password" | quote }}
  suite.idm_transport_user: {{ .Values.global.idm.transportUser | default "transport_admin" | quote }}
  suite.idm_organization: {{ .Values.global.idm.tenant | default "Provider" | quote }}
  suite.idm_addr: https://{{ (coalesce (include "helm-lib.getInternalIdmHost" .) .Values.global.idm.serviceName "itom-idm-svc") }}:{{ (coalesce (include "helm-lib.getInternalIdmPort" .) .Values.global.idm.internalPort "18443") }}
  suite.idm_external_url: https://{{ coalesce (include "helm-lib.getExternalIdmHost" .) .Values.global.externalAccessHost }}:{{ coalesce (include "helm-lib.getExternalIdmPort" .) .Values.global.externalAccessPort }}
