{{- if .Values.params.capability.reporting }}
apiVersion: v1
kind: Service
metadata:
  annotations:
    description: itom print service
  labels:
    service: webtopdf
  name: webtopdf
spec:
  ports:
  - name: p1
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    service: webtopdf
{{- end }}
