{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
apiVersion: networking.k8s.io/v1
{{ else if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1/Ingress" }}
apiVersion: networking.k8s.io/v1beta1
{{ else }}
apiVersion: extensions/v1beta1
{{ end -}}
kind: Ingress
metadata:
  name: nom-default-ingress
  annotations:
    {{ default "ingress.kubernetes.io" .Values.global.nginx.annotationPrefix }}/ingress.class: "nginx"
    {{ default "ingress.kubernetes.io" .Values.global.nginx.annotationPrefix }}/backend-protocol: HTTP
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: {{ required "Required value is not defined: externalAccessHost" .Values.global.externalAccessHost }}
    http:
      paths:
      - path: /static
        {{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
        pathType: Prefix
        backend:
          service:
            name: itom-nom-default-http-backend
            port: 
              number: 8080
        {{- else }}      
        backend:
          serviceName: itom-nom-default-http-backend
          servicePort: 8080
        {{- end }}  
