apiVersion: apps/v1
kind: Deployment
metadata:
  name: bvd-redis
  namespace: {{ .Release.Namespace }}
  annotations:
    deployment.microfocus.com/default-replica-count: "1"
    deployment.microfocus.com/runlevel: DB
  labels:
    service: bvd-redis
    app.kubernetes.io/name: bvd-redis
    app.kubernetes.io/managed-by: bvd-config
    app.kubernetes.io/version: {{ .Values.bvd.imageTag }}
    itom.microfocus.com/capability: bvd
    tier.itom.microfocus.com/redis: redis
spec:
  replicas: {{ .Values.redis.replicaCount }}
  selector:
    matchLabels:
      service: bvd-redis
      itom.microfocus.com/capability: bvd
  strategy: {}
  template:
    metadata:
      labels:
        service: bvd-redis
        itom.microfocus.com/capability: bvd
      annotations:
        {{- if .Values.global.vaultAppRole }}
        pod.boostport.com/vault-approle: {{ .Release.Namespace }}-{{ .Values.global.vaultAppRole }}
        {{- else }}
        pod.boostport.com/vault-approle: {{ .Release.Namespace }}-default
        {{- end }}
        pod.boostport.com/vault-init-container: install
    spec:
      serviceAccount: {{ .Values.deployment.rbac.serviceAccount }}
      serviceAccountName: {{ .Values.deployment.rbac.serviceAccount }}
      initContainers:
      {{- include "helm-lib.waitForVault" . | nindent 6 }}
      - name: install
        image: {{ .Values.global.docker.registry }}/{{ .Values.global.docker.orgName }}/{{ .Values.global.vaultInit.image }}:{{ .Values.global.vaultInit.imageTag }}
        env:
        {{- if .Values.global.vaultAppRole }}
        - name: "VAULT_ROLE_ID"
          value: "{{ .Values.global.vaultRoleId }}"
        {{- end }}
        - name: "CERT_COMMON_NAME"
          value: Realm:RID,Common_Name:bvd-redis,Additional_SAN:bvd-redis.{{ .Release.Namespace }}/bvd-redis.{{ .Release.Namespace }}.svc.cluster.local,File_Name:bvd-redis
        volumeMounts:
        - name: "vault-token"
          mountPath: /var/run/secrets/boostport.com
      containers:
      - image: {{ .Values.global.docker.registry }}/{{ .Values.global.docker.orgName }}/{{ ( coalesce .Values.global.itomRedis.image .Values.redis.image ) }}:{{ ( coalesce .Values.global.itomRedis.imageTag .Values.redis.imageTag ) }}
        livenessProbe:
          exec:
            command:
            - /bin/probeRedis.sh
          initialDelaySeconds: 5
          timeoutSeconds: 5
        name: bvd-redis
        env:
        - name: REDIS_CONF_KEY
          value: "redis_conf"
        - name: REDIS_PWD_KEY
          value: "redis_pwd"
        - name: CERT_COMMON_NAME
          value: "bvd-redis"
        - name: REDIS_APPENDONLY
          value: "no"
        ports:
        - containerPort: 6380
          protocol: TCP
        - containerPort: 9121
          name: redis-exporter
          protocol: TCP
        resources:
          requests:
            cpu: {{ .Values.redis.resources.requests.cpu }}
            memory: {{ .Values.redis.resources.requests.memory }}
          limits:
            memory: {{ .Values.redis.resources.limits.memory }}
            cpu: {{ .Values.redis.resources.limits.cpu }}
        volumeMounts:
          - name: bvd-redis-persistent-storage
            mountPath: /data
            subPath: redis-bvd/data
          - name: vault-token
            mountPath: /var/run/secrets/boostport.com
      - name: kubernetes-vault-renew
        image: {{ .Values.global.docker.registry }}/{{ .Values.global.docker.orgName }}/{{ .Values.global.vaultRenew.image }}:{{ .Values.global.vaultRenew.imageTag }}
        imagePullPolicy: {{ .Values.global.docker.imagePullPolicy }}
        volumeMounts:
          - name: vault-token
            mountPath: /var/run/secrets/boostport.com
      restartPolicy: Always
      securityContext:
        runAsNonRoot: true
        runAsUser: {{ .Values.global.securityContext.user | int64 }}
        runAsGroup: {{ .Values.global.securityContext.fsGroup | int64 }}
        fsGroup: {{ .Values.global.securityContext.fsGroup | int64 }}

      {{- with ( coalesce .Values.global.nodeSelector .Values.nodeSelector ) }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      volumes:
      - name: vault-token
        emptyDir: {}
      - name: bvd-redis-persistent-storage
        {{- include "helm-lib.pvcStorage" (dict "claim" "dbVolumeClaim" "Release" .Release "Template" .Template "Values" .Values ) | nindent 8 }}
