{{- if .Values.params.capability.reporting }}
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    description: itom print service server deployment
    deployment.microfocus.com/runlevel: UP
  labels:
    service: webtopdf
    app.kubernetes.io/name: webbtopdf
    app.kubernetes.io/managed-by: {{.Release.Name}}
    app.kubernetes.io/version: {{.Values.webtopdf.imageTag}}
  name: webtopdf-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      service: webtopdf
  template:
    metadata:
      labels:
        service: webtopdf
        app.kubernetes.io/name: webtopdf
        app.kubernetes.io/managed-by: {{.Release.Name}}
        app.kubernetes.io/version: {{.Values.webtopdf.imageTag}}
      annotations:
        {{- if .Values.global.vaultAppRole }}
        pod.boostport.com/vault-approle: {{ .Release.Namespace }}-{{ .Values.global.vaultAppRole }}
        {{- else }}
        pod.boostport.com/vault-approle: {{ .Release.Namespace }}-default
        {{- end }}
        pod.boostport.com/vault-init-container: install
        {{- if .Values.global.initSecrets }}
        secret.reloader.stakater.com/reload: "{{ .Values.global.initSecrets }}"
        {{- end }}
        {{- include "bvd.monitorConfigmap" (dict "Values" .Values) | nindent 8 }}


    spec:
      serviceAccount: {{ .Values.deployment.rbac.serviceAccount }}
      serviceAccountName: {{ .Values.deployment.rbac.serviceAccount }}
      securityContext:
        runAsNonRoot: true
        runAsUser: {{ .Values.global.securityContext.user }}
        fsGroup: {{ .Values.global.securityContext.fsGroup }}

      initContainers:
      {{- include "helm-lib.waitForVault" . | nindent 6 }}
      {{- include "helm-lib.waitFor" (dict "service" "bvd-controller" "port" 4000 "Values" .Values "addSecurityContext" true) | nindent 6 }}
      - name: install
        image: {{ .Values.global.docker.registry }}/{{ .Values.global.docker.orgName }}/{{ .Values.global.vaultInit.image }}:{{ .Values.global.vaultInit.imageTag }}
        env:
        {{- if .Values.global.vaultAppRole }}
        - name: VAULT_ROLE_ID
          value: {{ required "Required value not defined: vaultRoleId" .Values.global.vaultRoleId }}
        {{- end }}
        - name: CERT_COMMON_NAME
          value: Realm:RID,Common_Name:webtopdf,File_Name:webtopdf
        volumeMounts:
        - mountPath: /var/run/secrets/boostport.com
          name: vault-token

      containers:
      - name: webtopdf
        args:
        - webtopdf
        image: {{ .Values.global.docker.registry }}/{{ .Values.global.docker.orgName }}/{{ .Values.webtopdf.image }}:{{ .Values.webtopdf.imageTag }}
        imagePullPolicy: {{ .Values.global.docker.imagePullPolicy }}
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /webtopdf
            port: 3000
            scheme: HTTPS
          initialDelaySeconds: 1
          periodSeconds: 1
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        volumeMounts:
          - name: vault-token
            mountPath: /var/run/secrets/boostport.com
          {{ include "bvd.certificateSecret" (dict "args" "volumeMounts" "Values" .Values) }}
          {{ include "bvd.tlsTrustStore" (dict "args" "volumeMounts" "Values" .Values) }}
          {{ include "bvd.globalTlsTrustStore" (dict "args" "volumeMounts" "Values" .Values) }}
          {{ include "bvd.oracleWallet" (dict "args" "volumeMounts" "Values" .Values) }}
          - name: ips-reports
            mountPath: /var/ips/reports
            subPath: ips/reports
          - name: ips-bufferfiles
            mountPath: /var/ips/bufferFiles
            subPath: ips/bufferFiles
          - name: dshm
            mountPath: /dev/shm
        ports:
        - containerPort: 3000
        env:
        - name: DEBUG
          value: "bvd:error*"
        - name: NAMESPACE
          value: "{{ .Release.Namespace }}"
        - name: VAULT_ADDR
          value: "https://itom-vault:8200"
        - name: IDM_TRANSPORT_KEY
          value: {{ .Values.global.idm.transportUserKey | default "idm_transport_admin_password" | quote }}
        - name: IDM_TRANSPORT_USER
          value:  {{ .Values.global.idm.transportUser | default "transport_admin" | quote }}
        - name: IDM_ORGANIZATION
          value: {{ .Values.global.idm.tenant | default "Provider" | quote }}
        - name: EXTERNAL_NAME
          value: "{{ required "Must define externalAccessHost" .Values.global.externalAccessHost }}"
        - name: IDM_EXTERNAL_NAME
          value: {{ coalesce (include "helm-lib.getExternalIdmHost" .) .Values.global.externalAccessHost }}
        - name: "IDM_EXTERNAL_PORT"
          value: {{ coalesce (include "helm-lib.getExternalIdmPort" .) .Values.global.externalAccessPort | quote }}
        - name: "IPS_SERVER_PORT"
          value: "3000"
        - name: "BVD_IDM_INTEGRATION_USER"
          valueFrom:
            configMapKeyRef:
              name: bvd-services-config
              key: suite.integration_user
        - name: "BVD_IDM_INTEGRATION_USER_PASSWORD_KEY"
          valueFrom:
            configMapKeyRef:
              name: bvd-services-config
              key: suite.integration_user_password_key
        - name: REDIS_PWD_KEY
          valueFrom:
            configMapKeyRef:
              name: bvd-config
              key: bvd.redispassword.key
        - name: "EXTERNALPORT"
          valueFrom:
            configMapKeyRef:
              name: bvd-config
              key: bvd.externalport
        - name: "BVD_CONTEXT_ROOT"
          valueFrom:
            configMapKeyRef:
              name: bvd-config
              key: bvd.bvdContextRoot
        - name: "POSTGRES_PASSWORD_KEY"
          valueFrom:
            configMapKeyRef:
              name: bvd-config
              key: bvd.dbpassword.key
        - name: "BVD_DB_USER"
          valueFrom:
            configMapKeyRef:
              name: bvd-config
              key: bvd.dbuser
        - name: "BVD_DB_HOST"
          valueFrom:
            configMapKeyRef:
              name: bvd-config
              key: bvd.dbhost
        - name: "BVD_DB_PORT"
          valueFrom:
            configMapKeyRef:
              name: bvd-config
              key: bvd.dbport
        - name: "BVD_DB_NAME"
          valueFrom:
            configMapKeyRef:
              name: bvd-config
              key: bvd.dbname
        - name: "BVD_DB_TYPE"
          valueFrom:
            configMapKeyRef:
              name: bvd-config
              key: bvd.dbType
        - name: "BVD_DB_SID"
          valueFrom:
            configMapKeyRef:
              name: bvd-config
              key: bvd.dbsid
        - name: "BVD_DB_CONNECTION_STRING"
          valueFrom:
            configMapKeyRef:
              name: bvd-config
              key: bvd.dbConnectionString
        - name: "BVD_DB_CA_BASE64_KEY"
          valueFrom:
            configMapKeyRef:
              name: bvd-config
              key: bvd.dbCa.base64.key
        - name: "BVD_DB_CA_BASE64"
          valueFrom:
            configMapKeyRef:
              name: bvd-config
              key: bvd.dbCa.base64
        - name: "BVD_DB_USE_TLS"
          valueFrom:
            configMapKeyRef:
              name: bvd-config
              key: bvd.dbUseTLS
        - name: "BVD_USE_TLS"
          valueFrom:
            configMapKeyRef:
              name: bvd-config
              key: bvd.UseTLS
        - name: SMTP_HOST
          valueFrom:
            configMapKeyRef:
              name: bvd-config
              key: bvd.smtphost
              optional: true 
        - name: SMTP_PORT
          valueFrom:
            configMapKeyRef:
              name: bvd-config
              key: bvd.smtpport
              optional: true 
        - name: SMTP_SECURITY
          valueFrom:
            configMapKeyRef:
              name: bvd-config
              key: bvd.smtpsecurity
        - name: SMTP_USER
          valueFrom:
            configMapKeyRef:
              name: bvd-config
              key: bvd.smtpuser
              optional: true
        - name: SMTP_PASSWORD_KEY
          valueFrom:
            configMapKeyRef:
              name: bvd-config
              key: bvd.smtppassword.key
        - name: SYSTEM_USER_ID
          valueFrom:
            configMapKeyRef:
              name: bvd-config
              key: bvd.systemUID
        - name: SYSTEM_GROUP_ID
          valueFrom:
            configMapKeyRef:
              name: bvd-config
              key: bvd.systemGID
      - name: kubernetes-vault-renew
        image: {{ .Values.global.docker.registry }}/{{ .Values.global.docker.orgName }}/{{ .Values.global.vaultRenew.image }}:{{ .Values.global.vaultRenew.imageTag }}
        imagePullPolicy: {{ .Values.global.docker.imagePullPolicy }}
        volumeMounts:
        - name: vault-token
          mountPath: /var/run/secrets/boostport.com

      {{- with ( coalesce .Values.global.nodeSelector .Values.nodeSelector ) }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      volumes:
      - name: ips-reports
        {{- include "helm-lib.pvcStorage" (dict "claim" "configVolumeClaim" "Release" .Release "Template" .Template "Values" .Values ) | nindent 8 }}
      - name: ips-bufferfiles
        {{- include "helm-lib.pvcStorage" (dict "claim" "dataVolumeClaim" "Release" .Release "Template" .Template "Values" .Values ) | nindent 8 }}
      - name: vault-token
        emptyDir: {}
      {{ include "bvd.certificateSecret" (dict "args" "volumes" "Values" .Values) }}
      {{ include "bvd.tlsTrustStore" (dict "args" "volumes" "Values" .Values) }}
      {{ include "bvd.globalTlsTrustStore" (dict "args" "volumes" "Values" .Values) }}
      {{ include "bvd.oracleWallet" (dict "args" "volumes" "Values" .Values) }}
      - name: dshm
        emptyDir:
          medium: Memory
{{- end }}
