{{ if and (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1") .Values.global.prometheus.deployPrometheusConfig }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: itomdipulsar
    app.kubernetes.io/name: itomdipulsar-bookkeeper
    {{- include "servicemonitor.labels" . | nindent 4 }}
  name: itomdipulsar-bookkeeper
  namespace: {{ .Release.Namespace }}
spec:
  endpoints:
  - port: metrics
    path: /metrics
    scheme: http
    interval: 20s
    relabelings:
    {{- include "servicemonitor.relabelings" . | nindent 4 }}
    metricRelabelings:
    {{- include "servicemonitor.metricRelabelings" . | nindent 4 }}
  selector:
    matchLabels:
      app: itomdipulsar
      component: bookkeeper
  {{- include "servicemonitor.namespaceSelector" . | nindent 2 }}
{{ end }}