apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.nginx.secretName }}
  namespace: {{ .Release.Namespace }}
type: Opaque
{{- if and (.Values.global.tls.key) (.Values.global.tls.cert) }}
data:
  tls.key: {{ include "itom-nginx-ingress-controller.tlsKeyResolve" . }}
  tls.crt: {{ include "itom-nginx-ingress-controller.tlsCertResolve" . }}
{{- end }}