{{ $namePrefix := include "namePrefix" . }}
{{ $defaultBackendService := .Values.nginx.defaultBackendService }}
{{- if or (hasSuffix "frontend-ui" $defaultBackendService ) (hasSuffix "mng-portal" $defaultBackendService) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $namePrefix }}-nginx-ingress-template
data:
  {{- if hasSuffix "frontend-ui" $defaultBackendService }}
  {{- (.Files.Glob "cfg/nginx.tmpl").AsConfig | nindent 2 }}
  {{- else }}
  {{- (.Files.Glob "cfg/nginx-5443.tmpl").AsConfig | nindent 2 }}
  {{- end }}
{{- end }}
