apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
  name: nom-database-init
data:
  dbinit-script.sql: |
    create extension dblink; DO $do$ BEGIN
    IF EXISTS (SELECT FROM pg_database WHERE datname = 'APLS') THEN
    RAISE NOTICE 'Database already exists';
    ELSE
    PERFORM dblink_exec('dbname=' || current_database() , 'CREATE ROLE APLS PASSWORD NULL LOGIN');
    PERFORM dblink_exec('dbname=' || current_database() , 'CREATE DATABASE APLS OWNER APLS');
    END IF;
    {{- if .Values.global.bvd.isSelected }}
    IF EXISTS (SELECT FROM pg_database WHERE datname = 'BVD') THEN
    RAISE NOTICE 'Database already exists';
    ELSE
    PERFORM dblink_exec('dbname=' || current_database() , 'CREATE ROLE BVD PASSWORD NULL LOGIN');
    PERFORM dblink_exec('dbname=' || current_database() , 'CREATE DATABASE BVD OWNER BVD');
    END IF;
    {{- end }}
    IF EXISTS (SELECT FROM pg_database WHERE datname = 'IDM') THEN
    RAISE NOTICE 'Database already exists';
    ELSE
    PERFORM dblink_exec('dbname=' || current_database() , 'CREATE ROLE IDM PASSWORD NULL LOGIN');
    PERFORM dblink_exec('dbname=' || current_database() , 'CREATE DATABASE IDM OWNER IDM');
    END IF;
    {{- if .Values.global.containerizedMode }}
    IF EXISTS (SELECT FROM pg_database WHERE datname = 'NOM') THEN
    RAISE NOTICE 'Database already exists';
    ELSE
    PERFORM dblink_exec('dbname=' || current_database() , 'CREATE ROLE NOM PASSWORD NULL LOGIN');
    PERFORM dblink_exec('dbname=' || current_database() , 'CREATE DATABASE NOM OWNER NOM');
    END IF;

    IF EXISTS (SELECT * FROM pg_catalog.pg_namespace where nspname='nom') THEN
    RAISE NOTICE 'Schema already exists';
    ELSE
    PERFORM dblink_exec('dbname=nom', 'CREATE SCHEMA nom AUTHORIZATION nom');
    PERFORM dblink_exec('dbname=nom', 'SET search_path TO nom');
    END IF;

    {{- end }}
    IF EXISTS (SELECT FROM pg_database WHERE datname = 'BTCD') THEN
    RAISE NOTICE 'Database already exists';
    ELSE
    PERFORM dblink_exec('dbname=' || current_database() , 'CREATE ROLE BTCD PASSWORD NULL LOGIN');
    PERFORM dblink_exec('dbname=' || current_database() , 'CREATE DATABASE BTCD OWNER BTCD');
    END IF;
    END $do$;
