apiVersion: v1
kind: Service
metadata:
  labels:
    app: itomdischeduler
    app.kubernetes.io/name: itom-di-scheduler-svc
    app.kubernetes.io/managed-by: {{.Release.Name}}
    app.kubernetes.io/version: {{.Values.scheduler.imageTag}}
    itom.microfocus.com/capability: itom-data-ingestion
    tier.itom.microfocus.com/backend: backend
  name: itom-di-scheduler-svc
spec:
  ports:
    - name: scheduler-port
      port: {{.Values.scheduler.port}}
      protocol: TCP
      targetPort: 8443
    - name: metrics
      port: 5555
      protocol: TCP
      targetPort: 8443
  selector:
    app: itom-di-scheduler-udx