{{ $namePrefix := include "namePrefix" . }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $namePrefix }}-ingress-controller-conf
  namespace: {{ .Release.Namespace }}
data:
  {{- with .Values.nginx.configuration }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
---
{{- if and .Values.nginx.service.external.clientCertAuthPort (eq .Values.nginx.service.external.sslClientCertCAsCM "pki-auth-ca-certificates") }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: pki-auth-ca-certificates
data:
{{- end }}