apiVersion: apps/v1
kind: StatefulSet
metadata:
 # Statefulset name Pod name would be of $StatefulsetName-$ordinal
  name: itom-nom-metric-transformation
  labels:
    name: itom-nom-metric-transformation
  annotations:
    deployment.microfocus.com/default-replica-count: "1"
    deployment.microfocus.com/runlevel: UP
spec:
  #name of the service that governs this Statefuset.This service must exist before the Statefulset and is responsible for the
  #network identity of the set
  selector:
    matchLabels:
      name: itom-nom-metric-transformation
  serviceName: itom-nom-metric-transformation
  replicas: {{ .Values.deployment.replicas }}
  template:
    metadata:
      labels:
        name: itom-nom-metric-transformation
      annotations:
        {{- if .Values.global.vaultAppRole }}
        pod.boostport.com/vault-approle: {{ .Release.Namespace }}-{{ .Values.global.vaultAppRole }}
        {{- else }}
        pod.boostport.com/vault-approle: {{ .Release.Namespace }}-default
        {{- end }}
        pod.boostport.com/vault-init-container: install
    spec:
      serviceAccountName: itom-nom-metrics
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        runAsNonRoot: true
        runAsUser: {{ .Values.global.securityContext.user }}
        runAsGroup: {{ .Values.global.securityContext.fsGroup }}
        fsGroup: {{ .Values.global.securityContext.fsGroup }}
      terminationGracePeriodSeconds: 30
      initContainers:
      {{- $proxyHost := include "helm-lib.getDiPulsarProxyHost" . | default "itomdipulsar-proxy" }}
      {{- $proxyPort := include "helm-lib.getDiPulsarProxyClientPort" . | default "6651" }}
      {{- include "helm-lib.waitForVault" . | nindent 6 }}
      {{- include "helm-lib.waitFor" (dict "service" $proxyHost "port" $proxyPort "Values" .Values) | nindent 6 }}
      - name: install
        image: {{ .Values.global.docker.registry }}/{{ .Values.global.docker.orgName }}/{{ .Values.global.vaultInit.image }}:{{ .Values.global.vaultInit.imageTag }}
        env:
        {{- if .Values.global.vaultAppRole }}
        - name: VAULT_ROLE_ID
          value: {{ required "Required value is not defined: vaultRoleId" .Values.global.vaultRoleId | quote }}
        {{- end }}
        - name: CERT_COMMON_NAME
          value: Realm:RE,Common_Name:itom-nom-metric-transformation,Additional_SAN:{{ .Values.global.externalAccessHost }}/itom-nom-metric-transformation/itom-nom-metric-transformation.{{ .Release.Namespace }}
        volumeMounts:
        - mountPath: /var/run/secrets/boostport.com
          name: vault-token
      containers:
      - name: itom-nom-metric-transformation
        image: {{ .Values.global.docker.registry }}/{{ .Values.global.docker.orgName }}/{{ .Values.nomMetrics.image }}:{{ .Values.nomMetrics.imageTag }}
        imagePullPolicy: {{ .Values.global.docker.imagePullPolicy }}
        ports:
        - containerPort: 8443
        - containerPort: 8080
        - containerPort: 8686
        livenessProbe:
          httpGet:
            scheme: HTTPS
            path: /nom/api/metrics/v1/probe/
            port: 8443
          initialDelaySeconds: 90
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /nom/api/metrics/v1/probe/
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 30
          timeoutSeconds: 10
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        securityContext:
          readOnlyRootFilesystem: true
          capabilities:
            drop: ["CHOWN", "DAC_OVERRIDE", "FSETID", "FOWNER", "MKNOD", "SETGID", "SETUID", "SETFCAP", "SETPCAP", "NET_BIND_SERVICE", "SYS_CHROOT", "KILL", "AUDIT_WRITE","NET_RAW"]
        env:
          - name: SERVICE_ID
            value: "itom-nom-metric-transformer"
          - name: SERVICE_NAME
            value: "ITOM NOM Metric Transformer"
          - name: ZK_HOSTNAME
            {{- if .Values.global.opsbridgeIntegration.isSelected }}
            value: "itomdipulsar-zookeeper.{{.Release.Namespace}}"
            {{- else }}
            value: "nomzk-client-svc.{{.Release.Namespace}}"
            {{- end }}
          - name: ZK_PORT
            value: "2181"
          - name: ZK_NAMESPACE
            value: "nom"
          - name: NOM_ZK_ADMIN_PASSWORD_KEY
            value: NOM_ZK_ADMIN_PASSWORD_VAULT_KEY
          - name: LOG_PROPERTIES_LISTENER_ENABLED
            value: "true"
          - name: PULSAR_PROXY_SVC_NAME
            value: {{ include "helm-lib.getDiPulsarProxyHost" . | default "itomdipulsar-proxy" | quote }}
          - name: PULSAR_PROXY_CLIENT_PORT
            value: {{ include "helm-lib.getDiPulsarProxyClientPort" . | default "6651" | quote }}
          - name: PULSAR_PROXY_WEB_PORT
            value: {{ include "helm-lib.getDiPulsarProxyWebPort" . | default "8443" | quote }}
          - name: PULSAR_TOPIC_NAMESPACE
            value: "public"
          - name: PULSAR_TOPIC_TENANT
            value: "default"
          - name: TOPIC_PARTITION_COUNT
            value: {{ .Values.deployment.replicas  | quote }}
          - name: CONSUMER_SUBSCRIPTION_TYPE
            value: {{ .Values.baseline.consumerSubscriptionType | quote }}
          - name: BLOCK_IF_QUEUE_FULL
            value: {{ .Values.baseline.blockIfQueueFull | quote }}
          - name: COSO_TRANSFORMATION_CONCURRENCY
            value: {{ .Values.baseline.cosoTransformationConcurrency | quote }}
          - name: COSO_PULSAR_ACK_TIMEOUT
            value: {{ .Values.baseline.cosoPulsarAckTimeout | quote }}
          - name: COSO_TRANSFORMATION_QUEUE_LIMIT
            value: {{ .Values.baseline.cosoTransformationQueueLimit | quote }}
          - name: COSO_CONNECTION_INTERVAL
            value: {{ .Values.baseline.cosoConnectionInterval | quote }}
          - name: COSO_CONSUMER_SUBSCRIPTION_NAME
            value: "transformation"
          - name: COSO_PRODUCER_REPROCESSING_ENABLE
            value: "true"
          - name: MAX_MESSAGE_COUNT
            value: {{ .Values.baseline.maxMessageCount | quote }}
          - name: VIOLATION_FREE_WINDOW_TO_IGNORE_PROCESSING
            value: "20"
          - name: TRANSFORMATION_DB_MAX_READ_BATCH_SIZE
            value: {{ .Values.baseline.dbMaxReadBatchSize | quote }}
          - name: TRANSFORMATION_DB_MAX_READ_PARALLEL_THREADS
            value: {{ .Values.baseline.dbMaxReadParallelThreads | quote }}
          - name: TRANSFORMATION_DB_MAX_WRITE_BATCH_SIZE
            value: {{ .Values.baseline.dbMaxWriteBatchSize | quote }}
          - name: TRANSFORMATION_DB_MAX_WRITE_PARALLEL_THREADS
            value: {{ .Values.baseline.dbMaxWriteParallelThreads | quote }}
          - name: TRANSFORMATION_DB_CACHE_STATE_DELETE_INTERVAL_MIN
            value: {{ .Values.baseline.dbCacheStateDeleteIntervalMin | quote }}
          - name: TRANSFORMATION_DB_MIN_PERSIST_DELAY_INTERVAL_MIN
            value: {{ .Values.baseline.dbMinPersistDelayIntervalMin | quote }}
          - name: TRANSFORMATION_DB_PERSIST_INTERLEAVE_INTERVALS_ACROSS_PODS_MIN
            value: {{ .Values.baseline.dbPersistInterleaveIntervalsAcrossPodsMin | quote }}
          - name: TRANSFORMATION_DB_PERSIST_CYCLE_INTERVAL
            value: {{ .Values.baseline.dbPersistCycleInterval | quote }}
          - name: TRANSFORMATION_DB_CACHE_QUERY_HISTORY_LIMIT_MIN
            value: {{ .Values.baseline.dbCacheQueryHistoryLimitMin | quote }}
          - name: TRANSFORMATION_DB_CACHE_MAX_CONNECTIONS
            value: {{ .Values.baseline.dbCacheMaxConnections | quote }}
          - name: TRANSFORMATION_IN_MEMORY_INIT_CACHE_SIZE
            value: "10000000"
          - name: TRANSFORMATION_CACHE_SWEEP_ENABLED
            value: "true"
          - name: RE_FAILED_WRITER_FILE_MESSAGE_COUNT
            value: "1000"
          - name: RE_FAILED_WRITER_NEW_FILE_DIFF_INTERVAL_SEC
            value: "10"
          - name: RE_PUBLISH_FILE_MESSAGE_COUNT
            value: "1000"
          - name: RE_PUBLISH_FILE_PAUSE_INTERVAL_MSEC
            value: "1000"
          - name: RE_PUBLISH_MAX_FILE_COMPRESS_DELAY_MSEC
            value: "250"
          - name: RE_PUBLISH_MAX_FILES_TO_PROCESS
            value: "10000"
          - name: CACHE_DB_HOST
            value: {{ include "helm-lib.dbHost" . | quote }}
          - name: CACHE_DB_PORT
            value: {{ include "helm-lib.dbPort" . | quote }}
          - name: CACHE_DB_DATABASE
            value: {{ include "helm-lib.dbName" . | quote }}
          - name: CACHE_DB_USER
            value: {{ include "helm-lib.dbUser" . | quote }}
          - name: CACHE_DB_PASSWORD_KEY
            value: {{ include "helm-lib.dbUserKey" . | quote }}
          - name: CACHE_DB_IS_SSL
            value: {{ include "helm-lib.dbTlsEnabled" . | quote }}
          - name: CACHE_DB_SSL_MODE
            value: "verify-ca"
          - name: JVM_HEAP_MIN
            value: {{ .Values.baseline.jvmMin | quote }}
          - name: JVM_HEAP_MAX
            value: {{ .Values.baseline.jvmMax | quote }}
          - name: PARALLEL_GC_THREADS
            value: "4"
          - name: CONCURRENT_GC_THREADS
            value: "2"
          - name: MAX_GC_PAUSE_MSEC
            value: "500"
          - name: REPROCESS_INTERVAL
            value: {{ .Values.baseline.reprocessInterval | quote }}
          - name: REPROCESS_DELAY
            value: {{ .Values.baseline.reprocessDelay | quote }}
          - name: MCAST_ENABLED
            value: "{{ .Values.global.multicast.isSelected }}"
          - name: QA_ENABLED
            value: "{{ .Values.global.qa.isSelected }}"
          - name: REINIT_TRANFORMATION_CONFIG_RULES
            value: "true"
          - name: ITOM_CDF_EXTERNAL_SSL_CERTS_DIR
            value: /var/opt/OV/certs
        volumeMounts:
        - name: metric-transformation-log-vol
          mountPath: /var/opt/OV/log
          subPath: metric-transformation
        - name: metric-transformation-data-vol
          mountPath: /var/opt/OV
          subPath: metric-transformation
        - name: vault-token
          mountPath: /var/run/secrets/boostport.com
        - name: temp
          mountPath: /tmp
        {{- if .Values.global.database.tlsTruststore }}
        - name: certs-volume
          mountPath: /var/opt/OV/certs
        {{- else }}
        - name: metric-transformation-data-vol
          mountPath: /var/opt/OV/certs
          subPath: nom/certificates
        {{- end }}
      - env:
        - name: CERT_FILE_BASE_NAME
          value: RE/server
        - name: PROXY_LISTENING_PORT
          value: "8787"
        - name: PROXY_TARGET_PORT
          value: "8686"
        image: {{ .Values.global.docker.registry }}/{{ .Values.global.docker.orgName }}/{{ .Values.sTunnel.image }}:{{ .Values.sTunnel.imageTag }}
        imagePullPolicy: IfNotPresent
        name: stunnel
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 1m
            memory: 50Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: vault-token
          mountPath: /var/run/secrets/boostport.com
      - name: kubernetes-vault-renew
        image: {{ .Values.global.docker.registry }}/{{ .Values.global.docker.orgName }}/{{ .Values.global.vaultRenew.image }}:{{ .Values.global.vaultRenew.imageTag }}
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: vault-token
          mountPath: /var/run/secrets/boostport.com
      restartPolicy: Always
      volumes:
      - name: metric-transformation-data-vol
        {{- include "helm-lib.pvcStorage" (dict "claim" "dataVolumeClaim" "Release" .Release "Template" .Template "Values" .Values ) | nindent 8 }}
      - name: metric-transformation-log-vol
        {{- include "helm-lib.pvcStorage" (dict "claim" "logVolumeClaim" "Release" .Release "Template" .Template "Values" .Values ) | nindent 8 }}
      {{- if .Values.global.database.tlsTruststore }}
      - name: certs-volume
        configMap:
          name: {{ .Values.global.database.tlsTruststore }}
      {{- end }}
      - name: vault-token
        emptyDir: {}
      - name: temp
        emptyDir: {}

      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
 
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
