apiVersion: v1
kind: Service
metadata:
  name: itom-nom-metric-transformation
  labels:
    name: itom-nom-metric-transformation
    app.kubernetes.io/name: itom-nom-metric-transformation
    app.kubernetes.io/managed-by: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Values.nomMetrics.imageTag }}
    itom.microfocus.com/capability: itom-nom-metric-transformation
    tier.itom.microfocus.com/backend: backend
spec:
  ports:
  - port: 8443
    protocol: TCP
    name: metric-transformation-https
    targetPort: 8443
  - name: jmx-exporter-https
    port: 8686
    protocol: TCP
    targetPort: 8787
  selector:
    name: itom-nom-metric-transformation
