dependencies:
- name: redis
  version: 17.x.x
  repository: https://charts.bitnami.com/bitnami
- name: postgresql
  version: 11.x.x
  repository: https://charts.bitnami.com/bitnami
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
    - bitnami-common
  version: 2.x.x