apiVersion: v2
appVersion: "2021.11"
publico: false
dependencies:
- name: helm-lib
  version: 1.5.28
- name: itom-ingress-controller
  version: 1.5.49
- name: nomhttp
  version: 1.0.55
- name: itom-vault
  version: 1.6.98
- name: itom-vault-client
  version: 1.2.8
- name: itom-reloader
  version: 1.2.32
- name: idm
  version: 1.6.100
- name: nomcore
  version: 1.0.68
- condition: global.database.internal
  name: postgres
  version: 1.0.94
- name: autopass
  version: 12.2.06
- name: nomzk
  version: 1.0.48
- name: nomxui
  version: 3.4.77
- name: nomapiserver
  version: 1.1.192
- condition: global.telemetry.isSelected
  name: nom-telemetry
  version: 0.0.37
- condition: global.vertica.embedded
  name: itomdisharedvertica
  version: 10.1.1-7-14
- condition: global.coso.isSelected
  name: itomdiadministration
  version: 2.5.0-46
- condition: global.coso.isSelected
  name: itomdidataaccess
  version: 2.5.0-34
- condition: global.coso.isSelected
  name: itomdimetadataserver
  version: 2.5.0-25
- condition: global.coso.isSelected
  name: itomdipulsar
  version: 2.8.1-31
- condition: global.coso.isSelected
  name: itomdipostload
  version: 2.5.0-50
- condition: global.coso.isSelected
  name: itom-di-udx-scheduler
  version: 2.5.0-33
- condition: global.minio.isSelected
  name: itomdiminio
  version: 2.5.0-21
- condition: global.cosoMonitoring.isSelected
  name: itomdimonitoring
  version: 2.5.0-61
- condition: global.bvd.isSelected
  name: bvd
  version: 11.8.11
- name: nomreportingcontent
  version: 1.4.135
- name: itomnomcosodataaccess
  version: 1.4.46
- condition: global.coso.isSelected
  name: nommetricstransform
  version: 1.4.90
description: Micro Focus Network Operations Management - Ultimate Edition
maintainers:
- email: robert.balser@microfocus.com
  name: robert
name: nomultimate
version: 1.5.4
# version: 1.5.0+20211100.162