#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

{{ if .Values.components.proxy -}}
{{- include "pulsar.setCurrentComponentFull" (set . "currentComponent" .Values.proxy.component) -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .currentComponentFull }}"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pulsar.standardLabels" . | nindent 4 }}
  annotations:
    {{- include "pulsar.template.annotations" . | nindent 4 }}
    {{- include "pulsar.template.reloaderannotations" . | nindent 4 }}
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1        # how many pods we can add at a time
      maxUnavailable: 1
  replicas: {{ .Values.proxy.replicaCount }}
  selector:
    matchLabels:
      {{- include "pulsar.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "pulsar.standardLabels" . | nindent 8 }}
      annotations:
        pod.boostport.com/vault-init-container: generate-certificates
        {{- if .Values.global.vaultAppRole }}
        pod.boostport.com/vault-approle: {{ .Release.Namespace }}-{{ .Values.global.vaultAppRole }}
        {{- else }}
        pod.boostport.com/vault-approle: {{ .Release.Namespace }}-default
        {{- end }}
        prometheus.io/scrape: "true"
        {{- if and .Values.tls.enabled .Values.tls.proxy.enabled }}
        prometheus.io/port: "{{ .Values.proxy.ports.https }}"
        {{- else }}
        prometheus.io/port: "{{ .Values.proxy.ports.http }}"
        {{- end }}
        {{- if .Values.proxy.autoRollDeployment }}
        checksum/config: {{ include (print $.Template.BasePath "/proxy/proxy-configmap.yaml") . | sha256sum }}
        {{- end }}
        {{- include "pulsar.template.annotations" . | nindent 8 }}
{{- with .Values.proxy.annotations }}
{{ toYaml . | indent 8 }}
{{- end }}
    spec:
      securityContext:
        runAsUser: {{ .Values.global.securityContext.user | int64 }}
        runAsGroup: {{ .Values.global.securityContext.group | int64 }}
        fsGroup: {{ .Values.global.securityContext.fsGroup | int64 }}
      {{- with ( coalesce .Values.nodeSelector .Values.global.nodeSelector ) }}
      nodeSelector:
        {{ toYaml . }}
      {{- end }}
    {{- if .Values.proxy.tolerations }}
      tolerations:
{{ toYaml .Values.proxy.tolerations | indent 8 }}
    {{- end }}

      serviceAccount: {{ .Values.deployment.rbac.proxyServiceAccount | default "itomdipulsar-sa" }}
      serviceAccountName: {{ .Values.deployment.rbac.proxyServiceAccount | default "itomdipulsar-sa" }}
      {{ if eq (include  "pulsar.is_cloud_deployment" . ) "true" -}}
      {{ if .Values.proxy.topologySpreadConstraints.enabled -}}
      topologySpreadConstraints:
      - maxSkew: {{ .Values.proxy.topologySpreadConstraints.maxSkew | default 1 }}
        topologyKey: {{ .Values.proxy.topologySpreadConstraints.topologyKey | default "topology.kubernetes.io/zone" }}
        whenUnsatisfiable: {{ .Values.proxy.topologySpreadConstraints.whenUnsatisfiable | default "ScheduleAnyway" }}
        labelSelector:
          matchLabels:
            component: {{ .Values.proxy.component }}
      {{- end }}
      {{- end }}
      affinity:
        {{- if and .Values.affinity.anti_affinity .Values.proxy.affinity.anti_affinity}}
        podAntiAffinity:
          {{ .Values.proxy.affinity.type }}:
          {{ if eq .Values.proxy.affinity.type "requiredDuringSchedulingIgnoredDuringExecution"}}
          - labelSelector:
              matchExpressions:
              - key: "app"
                operator: In
                values:
                - "{{ template "pulsar.name" . }}"
              - key: "release"
                operator: In
                values:
                - {{ .Release.Name }}
              - key: "component"
                operator: In
                values:
                - {{ .currentComponent }}
            topologyKey: "kubernetes.io/hostname"
          {{ else }}
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: "app"
                      operator: In
                      values:
                      - "{{ template "pulsar.name" . }}"
                    - key: "release"
                      operator: In
                      values:
                      - {{ .Release.Name }}
                    - key: "component"
                      operator: In
                      values:
                      - {{ .currentComponent }}
                topologyKey: "kubernetes.io/hostname"
          {{ end }}
        {{- end }}
      terminationGracePeriodSeconds: {{ .Values.proxy.gracePeriod }}
      initContainers:
    {{- include "helm-lib.waitForVault" . | nindent 6 }}
      # This init container will generate certificates.
      - name: generate-certificates
    {{- if and .Values.global.vaultInit.registry .Values.global.vaultInit.orgName }}
        image: {{ .Values.global.vaultInit.registry }}/{{ .Values.global.vaultInit.orgName }}/{{ .Values.global.vaultInit.image }}:{{ .Values.global.vaultInit.imageTag }}
    {{- else}}
        image: {{ .Values.global.docker.registry }}/{{ .Values.global.docker.orgName }}/{{ .Values.global.vaultInit.image }}:{{ .Values.global.vaultInit.imageTag }}
    {{- end}}
        # command: ["sh", "-c"]
        # args:
        # - >
        #   sleep 5
        imagePullPolicy: IfNotPresent
        env:
          - name: CERT_COMMON_NAME
            value: "Realm:RID,Common_Name:{{ .Values.global.externalAccessHost }},Additional_SAN:{{ .currentComponentFull }};Realm:RE,Common_Name:{{ .Values.global.externalAccessHost }},Additional_SAN:{{ .currentComponentFull }}/{{ .currentComponentFull }}.{{ .Release.Namespace }}/{{ .currentComponentFull }}.{{ .Release.Namespace }}.svc"
        volumeMounts:
        - name: vault-token
          mountPath: /var/run/secrets/boostport.com
      {{- include "pulsar.zookeeper.wait.init.node" . | nindent 6}}
      # This init container will wait for at least one broker to be ready before
      # deploying the proxy
      - name: wait-broker-ready
        image: {{ .Values.global.docker.registry }}/{{ .Values.global.docker.orgName }}/{{ .Values.pulsar.image }}:{{ .Values.pulsar.imageTag }}
        imagePullPolicy: {{ .Values.global.docker.imagePullPolicy }}
        command: ["sh", "-c"]
        args:
          - >-
            source bin/coso-init.sh;
            set -e;
            brokerServiceNumber="$(nslookup -timeout=10 {{ template "pulsar.fullname" . }}-{{ .Values.broker.component }} | grep Name | wc -l)";
            until [ ${brokerServiceNumber} -ge 1 ]; do
              echo "pulsar cluster {{ template "pulsar.fullname" . }} isn't initialized yet ... check in 10 seconds ...";
              sleep 10;
              brokerServiceNumber="$(nslookup -timeout=10 {{ template "pulsar.fullname" . }}-{{ .Values.broker.component }} | grep Name | wc -l)";
            done;
        volumeMounts:
        - name: tmp
          mountPath: /pulsar/tmp
        - name: conf
          mountPath: /pulsar/conf
        - name: logs
          mountPath: /pulsar/logs
        - name: ssl
          mountPath: /pulsar/ssl
        - name: vault-token
          mountPath: /var/run/secrets/boostport.com
        {{- include "pulsar.coso.init.volumeMounts" . | nindent 8 }}
{{- with .Values.common.extraInitContainers }}
{{ toYaml . | indent 6 }}
{{- end }}
{{- with .Values.proxy.extraInitContainers }}
{{ toYaml . | indent 6 }}
{{- end }}
      containers:
      - name: certificate-renew
      {{- if and .Values.global.vaultRenew.registry .Values.global.vaultRenew.orgName }}
        image: {{ .Values.global.vaultRenew.registry }}/{{ .Values.global.vaultRenew.orgName }}/{{ .Values.global.vaultRenew.image }}:{{ .Values.global.vaultRenew.imageTag }}
      {{- else }}
        image: {{ .Values.global.docker.registry }}/{{ .Values.global.docker.orgName }}/{{ .Values.global.vaultRenew.image }}:{{ .Values.global.vaultRenew.imageTag }}
      {{- end }}
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: vault-token
          mountPath: /var/run/secrets/boostport.com
      - name: "{{ .currentComponentFull }}"
        image: {{ .Values.global.docker.registry }}/{{ .Values.global.docker.orgName }}/{{ .Values.pulsar.image }}:{{ .Values.pulsar.imageTag }}
        imagePullPolicy: {{ .Values.global.docker.imagePullPolicy }}
        {{- if .Values.proxy.probe.liveness.enabled }}
        livenessProbe:
{{ include "pulsar.proxy.probe" . | indent 10 }}
          initialDelaySeconds: {{ .Values.proxy.probe.liveness.initialDelaySeconds }}
          periodSeconds: {{ .Values.proxy.probe.liveness.periodSeconds }}
          timeoutSeconds: {{ .Values.proxy.probe.liveness.timeoutSeconds }}
          failureThreshold: {{ .Values.proxy.probe.liveness.failureThreshold }}
          successThreshold: {{ .Values.proxy.probe.liveness.successThreshold }}
        {{- end }}
        {{- if .Values.proxy.probe.readiness.enabled }}
        readinessProbe:
{{ include "pulsar.proxy.probe" . | indent 10 }}
          initialDelaySeconds: {{ .Values.proxy.probe.readiness.initialDelaySeconds }}
          periodSeconds: {{ .Values.proxy.probe.readiness.periodSeconds }}
          timeoutSeconds: {{ .Values.proxy.probe.readiness.timeoutSeconds }}
          failureThreshold: {{ .Values.proxy.probe.readiness.failureThreshold }}
          successThreshold: {{ .Values.proxy.probe.readiness.successThreshold }}
        {{- end }}
        {{- if .Values.proxy.probe.startup.enabled }}
        startupProbe:
{{ include "pulsar.proxy.probe" . | indent 10 }}
          initialDelaySeconds: {{ .Values.proxy.probe.startup.initialDelaySeconds }}
          periodSeconds: {{ .Values.proxy.probe.startup.periodSeconds }}
          timeoutSeconds: {{ .Values.proxy.probe.startup.timeoutSeconds }}
          failureThreshold: {{ .Values.proxy.probe.startup.failureThreshold }}
          successThreshold: {{ .Values.proxy.probe.startup.successThreshold }}
        {{- end }}
      {{- if .Values.proxy.resources }}
        resources:
{{ toYaml .Values.proxy.resources | indent 10 }}
      {{- end }}
        command: ["sh", "-c"]
        args:
        - >
          source bin/coso-init.sh;
          bin/apply-config-from-env.py conf/proxy.conf conf/client.conf;
          echo "OK" > /pulsar/tmp/status;
          bin/pulsar proxy;
        ports:
        # prometheus needs to access /metrics endpoint
        - name: http
          containerPort: {{ .Values.proxy.ports.http }}
        {{- if or (not .Values.tls.enabled) (not .Values.tls.proxy.enabled) }}
        - name: pulsar
          containerPort: {{ .Values.proxy.ports.pulsar }}
        {{- end }}
        {{- if and (.Values.tls.enabled) (.Values.tls.proxy.enabled) }}
        - name: https
          containerPort: {{ .Values.proxy.ports.https }}
        - name: pulsarssl
          containerPort: {{ .Values.proxy.ports.pulsarssl }}
        {{- end }}
        envFrom:
        - configMapRef:
            name: "{{ .currentComponentFull }}"
        volumeMounts:
          - name: tmp
            mountPath: /pulsar/tmp
          - name: conf
            mountPath: /pulsar/conf
          - name: logs
            mountPath: /pulsar/logs
          - name: ssl
            mountPath: /pulsar/ssl
          - name: vault-token
            mountPath: /var/run/secrets/boostport.com
          {{- include "pulsar.coso.init.volumeMounts" . | nindent 10 }}
          {{- include "pulsar.coso.externalcert.volumeMounts" . | nindent 10 }}
          {{- include "pulsar.proxy.log.volumeMounts" . | nindent 10 }}
          {{- include "pulsar.proxy.certs.volumeMounts" . | nindent 10 }}
      volumes:
        - name: tmp
          emptyDir: {}
        - name: conf
          emptyDir: {}
        - name: ssl
          emptyDir: {}
        - name: logs
          emptyDir: {}
        - name: vault-token
          emptyDir: {}
        {{- include "pulsar.coso.init.volumes" . | nindent 8 }}
        {{- include "pulsar.coso.externalcert.volumes" . | nindent 8 }}
        {{- include "pulsar.proxy.log.volumes" . | nindent 8 }}
        {{- include "pulsar.proxy.certs.volumes" . | nindent 8 }}
{{- end }}
