clusterK8s:
  name: ${{ secrets.CLUSTER_NAME_ARGO}}
  server: ${{ secrets.CLUSTER_URL_ARGO}}
  source: https://github.com/ederqueirozdf/k8s-cobaia.git
  extraApi: 
    - namespace: "*"
      server: ${{ secrets.CLUSTER_URL_ARGO}}

argocd:
  namespace: argocd
  disablePrune: false

# #####################################################################
# APPS
# #####################################################################

  apps:
    - name: "guestbook"
      finalizers: []
      labels: []
        # - key: chave
        #   value: valor
      annotations: []
        # - key: chave
        #   value: valor
      spec:
        project: k8s-cobaia
        source:
          path: aplic/guestbook
          repoURL: https://github.com/ederqueirozdf/k8s-cobaia.git
          targetRevision: HEAD     
        destination:
          namespace: cobaia-guestbook
          server: ${{ secrets.CLUSTER_URL_ARGO}}
        syncPolicy:
          automated:
            prune: true
            selfHeal: true

# #####################################################################
# MONITOR
# #####################################################################

    # - name: "thanos"
    #   finalizers: []
    #   labels: []
    #     # - key: chave
    #     #   value: valor
    #   annotations: []
    #     # - key: chave
    #     #   value: valor
    #   spec:
    #     project: k8s-cobaia
    #     source:
    #       path: aplic/thanos
    #       repoURL: https://github.com/ederqueirozdf/k8s-cobaia.git
    #       targetRevision: HEAD 
    #     destination:
    #       namespace: cobaia-thanos
    #       server: $CLUSTER_URL_ARGO
    #     syncPolicy:
    #       automated:
    #         prune: true
    #         selfHeal: true

    # - name: "prometheus-master-0"
    #   finalizers: []
    #   labels: []
    #     # - key: chave
    #     #   value: valor
    #   annotations: []
    #     # - key: chave
    #     #   value: valor
    #   spec:
    #     project: k8s-cobaia
    #     source:
    #       path: aplic/prometheus-master-0
    #       repoURL: https://github.com/ederqueirozdf/k8s-cobaia.git
    #       targetRevision: HEAD 
    #     destination:
    #       namespace: cobaia-prometheus-master-0
    #       server: $CLUSTER_URL_ARGO
    #     syncPolicy:
    #       automated:
    #         prune: true
    #         selfHeal: true

    # - name: "minio"
    #   finalizers: []
    #   labels: []
    #     # - key: chave
    #     #   value: valor
    #   annotations: []
    #     # - key: chave
    #     #   value: valor
    #   spec:
    #     project: k8s-cobaia
    #     source:
    #       path: aplic/minio
    #       repoURL: https://github.com/ederqueirozdf/k8s-cobaia.git
    #       targetRevision: HEAD 
    #     destination:
    #       namespace: cobaia-minio
    #       server: $CLUSTER_URL_ARGO
    #     syncPolicy:
    #       automated:
    #         prune: true
    #         selfHeal: true

    # - name: "velero"
    #   finalizers: []
    #   labels: []
    #     # - key: chave
    #     #   value: valor
    #   annotations: []
    #     # - key: chave
    #     #   value: valor
    #   spec:
    #     project: k8s-cobaia
    #     source:
    #       path: aplic/velero
    #       repoURL: https://github.com/ederqueirozdf/k8s-cobaia.git
    #       targetRevision: HEAD 
    #     destination:
    #       namespace: cobaia-velero
    #       server: $CLUSTER_URL_ARGO
    #     syncPolicy:
    #       automated:
    #         prune: true
    #         selfHeal: true            