clusterK8s:
  name: "k8s-lab"
  server: https://kubernetes.default.svc
  source: https://github.com/ederqueirozdf/k8s-cobaia.git
  extraApi: 
    - namespace: "*"
      server: https://kubernetes.default.svc 

argocd:
  namespace: argocd
  disablePrune: false

# ########
# APPS
# ########

  apps:

# #####################################################################
# BACKUP
# #####################################################################

    - name: "guestbook"
      finalizers: []
      labels: []
        # - key: chave
        #   value: valor
      annotations: []
        # - key: chave
        #   value: valor
      spec:
        project: default
        source:
          path: aplic/guestbook
          repoURL: https://github.com/ederqueirozdf/k8s-cobaia.git
          targetRevision: HEAD 
        destination:
          namespace: guestbook
          server: https://kubernetes.default.svc
        syncPolicy:
          automated:
            prune: true
            selfHeal: true            