clusterK8s:
  name: "k8s-ocp-equeiroz"
  server: https://kubernetes.default.svc
  source: https://github.com/ederqueirozdf/k8s-cobaia.git
  extraApi: 
    - namespace: "*"
      server: https://kubernetes.default.svc 

argocd:
  namespace: openshift-gitops
  disablePrune: false

# ########
# APPS
# ########

  apps:
    - name: "guestbook"
      finalizers: []
      labels:
        - app: guestbook
        #   value: valor
      annotations: []
        # - key: chave
        #   value: valor
      spec:
        project: default
        source:
          path: aplic/guestbook
          repoURL: https://github.com/ederqueirozdf/k8s-cobaia.git
          targetRevision: HEAD
          helm:
            valueFiles:
              - values.yaml
        destination:
          namespace: guestbook
          server: https://kubernetes.default.svc
        syncPolicy:
          automated:
            prune: true
            selfHeal: true