{{ $namePrefix := include "namePrefix" . }}
{{- if .Values.global.rbac.serviceAccountCreate}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $namePrefix }}-postgresql
  namespace: {{ .Release.Namespace }}
imagePullSecrets:
  - name: {{ .Values.global.docker.imagePullSecret | default "registrypullsecret" }}
{{- end }}
---
{{- if .Values.global.rbac.roleCreate}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $namePrefix }}-postgresql
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - serviceaccounts
      - configmaps
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
      - deletecollection

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $namePrefix }}-postgresql:{{ $namePrefix }}-postgresql
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $namePrefix }}-postgresql
subjects:
  - kind: ServiceAccount
    name: {{ $namePrefix }}-postgresql
    namespace: {{ .Release.Namespace }}
{{- end }}