{{- if or (.Values.global.coso.isSelected) (.Values.global.perfTroubleshooting.isSelected) }}
apiVersion: v1
kind: Service
metadata:
  name: itom-coso-dl-data-access
  labels:
    name: itom-coso-dl-data-access
    {{- if .Values.global.database.tlsTruststore }}
    configmap.reloader.stakater.com/reload: {{ .Values.global.database.tlsTruststore | quote }}
    {{- end }}
spec:
  ports:
    - port: 8443
      protocol: TCP
      name: itom-coso-dl-data-access-https
      targetPort: 8443
  selector:
    name: itom-coso-dl-data-access
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: itom-coso-dl-data-access
  labels:
    name: itom-coso-dl-data-access
  annotations:
    deployment.microfocus.com/default-replica-count: "1"
    deployment.microfocus.com/runlevel: UP
spec:
  selector:
    matchLabels:
      name: itom-coso-dl-data-access
  serviceName: itom-coso-dl-data-access
  template:
    metadata:
      labels:
        name: itom-coso-dl-data-access
      annotations:
        {{- if .Values.global.vaultAppRole }}
        pod.boostport.com/vault-approle: {{ .Release.Namespace }}-{{ .Values.global.vaultAppRole }}
        {{- else }}
        pod.boostport.com/vault-approle: {{ .Release.Namespace }}-default
        {{- end }}
        pod.boostport.com/vault-init-container: install
    spec:
      serviceAccountName: itom-nom-coso-dl
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
 
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
 
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      securityContext:
        runAsNonRoot: true
        runAsUser: {{ .Values.global.securityContext.user }}
        runAsGroup: {{ .Values.global.securityContext.fsGroup }}
        fsGroup: {{ .Values.global.securityContext.fsGroup }}
      terminationGracePeriodSeconds: 30
      initContainers:
        {{- include "helm-lib.waitForVault" . | nindent 8 }}
        - name: install
          image: {{ .Values.global.docker.registry }}/{{ .Values.global.docker.orgName }}/{{ .Values.global.vaultInit.image }}:{{ .Values.global.vaultInit.imageTag }}
          env:
            {{- if .Values.global.vaultAppRole }}
            - name: VAULT_ROLE_ID
              value: {{ required "Required value not defined: vaultRoleId" .Values.global.vaultRoleId }}
            {{- end }}
            - name: CERT_COMMON_NAME
              value: itom-coso-dl-data-access
          volumeMounts:
            - mountPath: /var/run/secrets/boostport.com
              name: vault-token
      containers:
        {{ $apHost := include "helm-lib.getAplsHost" . | default "itom-autopass-lms" }}
        {{ $apPort := include "helm-lib.getAplsPort" . | default 5814 }}
        - name: itom-coso-dl-data-access
          image: {{ .Values.global.docker.registry }}/{{ .Values.global.docker.orgName }}/{{ .Values.dataAccess.image }}:{{ .Values.dataAccess.imageTag }}
          imagePullPolicy: {{ .Values.global.docker.imagePullPolicy }}
          ports:
            - containerPort: 8443
            - containerPort: 8080
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /health/
              port: 8443
            initialDelaySeconds: 20
            timeoutSeconds: 10
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /health/
              port: 8443
            initialDelaySeconds: 5
            timeoutSeconds: 15
            periodSeconds: 5
            failureThreshold: 2
          resources:
            limits:
              cpu: "2"
              memory: "1024Mi"
            requests:
              cpu: "100m"
              memory: "512Mi"
          securityContext:
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["CHOWN", "DAC_OVERRIDE", "FSETID", "FOWNER", "MKNOD", "SETGID", "SETUID", "SETFCAP", "SETPCAP", "NET_BIND_SERVICE", "SYS_CHROOT", "KILL", "AUDIT_WRITE","NET_RAW"]
          env:
            - name: SERVICE_ID
              value: "itom-coso-dl-data-access"
            - name: SERVICE_NAME
              value: "ITOM COSO DL Data Access"
            - name: ZK_HOSTNAME
              {{- if .Values.global.opsbridgeIntegration.isSelected }}
              value: "itomdipulsar-zookeeper.{{.Release.Namespace}}"
              {{- else }}
              value: "nomzk-client-svc.{{.Release.Namespace}}"
              {{- end }}
            - name: ZK_PORT
              value: "2181"
            - name: ZK_NAMESPACE
              value: "nom"
            - name: NOM_ZK_ADMIN_PASSWORD_KEY
              value: NOM_ZK_ADMIN_PASSWORD_VAULT_KEY
            - name: APLS_HOST
              value: {{ $apHost | quote }}
            - name: APLS_PORT
              value: {{ $apPort | quote }}
            # This product id changes only when there is change in license pd file
            - name: NOM_PRODUCT_ID
              value: {{ .Values.global.nom.nomProductId }}
            - name: LICENSE_CHECK_INTERVAL
              value: "15"
            {{- if .Values.global.coso.isSelected }}
            {{- if .Values.global.vertica.embedded }}
            - name: METRIC_SCHEMA
              value: {{ printf "mf_shared_%s_%s" .Values.global.di.tenant .Values.global.di.deployment | quote }}
            - name: COSO_DATABASE_SCHEMA
              value: {{ printf "mf_shared_%s_%s" .Values.global.di.tenant .Values.global.di.deployment | quote }}
            # Vertica Database Specific Environment Variables
            - name: COSO_DATABASE_HOST
              value: "itom-di-vertica-svc"
            - name: COSO_DATABASE_PORT
              value: "5444"
            - name: COSO_DATABASE_SSL
              value: "true"
            - name: COSO_DATABASE_DB
              value: "itomdb"
            - name: COSO_DATABASE_USER
              value: "dbadmin"
            - name: COSO_DATABASE_PASSWORD_KEY
              value: "ITOMDI_DBA_PASSWORD_KEY"
            - name: COSO_DATABASE_RW_USER
              value: "dbadmin"
            - name: COSO_DATABASE_RW_PASSWORD_KEY
              value: "ITOMDI_DBA_PASSWORD_KEY"
            {{- else }}
            - name: METRIC_SCHEMA
              value: {{ printf "mf_shared_%s_%s" .Values.global.di.tenant .Values.global.di.deployment | quote }}
            - name: COSO_DATABASE_SCHEMA
              value: {{ printf "mf_shared_%s_%s" .Values.global.di.tenant .Values.global.di.deployment | quote }}
            # Vertica Database Specific Environment Variables
            - name: COSO_DATABASE_HOST
              value: {{ required "Must provide Vertica host" .Values.global.vertica.host | quote }}
            - name: COSO_DATABASE_PORT
              value: {{ required "Must provide Vertica port" .Values.global.vertica.port | quote }}
            - name: COSO_DATABASE_SSL
              value: {{ .Values.global.vertica.tlsEnabled | quote }}
            - name: COSO_DATABASE_DB
              value: {{ required "Must provide Vertica DB name" .Values.global.vertica.db | quote }}
            - name: COSO_DATABASE_USER
              value: {{ required "Must provide Vertica user name with read-only access" .Values.global.vertica.rouser | quote }}
            - name: COSO_DATABASE_PASSWORD_KEY
              value: {{ required "Must provide Vertica password key for vertica read-only access" .Values.global.vertica.rouserkey | quote }}
            - name: COSO_DATABASE_RW_USER
              value: {{ required "Must provide Vertica user name with read-write access" .Values.global.vertica.rwuser | quote }}
            - name: COSO_DATABASE_RW_PASSWORD_KEY
              value: {{ required "Must provide Vertica password key for read-write access" .Values.global.vertica.rwuserkey | quote }}
            {{- end }}
            - name: COSO_DB_METADATA_SCHEMA
              value: "itom_di_metadata_provider_default"
            - name: COSO_DB_CONFIG_SCHEMA
              value: "itom_di_configuration_provider_default"
            - name: COSO_DATABASE_CONNECTION_MIN_IDLE
              value: "10"
            - name: COSO_DATABASE_CONNECTION_MAX_IDLE
              value: "10"
            - name: COSO_DATABASE_CONNECTION_TOTAL
              value: "20"
            - name: COSO_DATABASE_RW_CONNECTION_MIN_IDLE
              value: "6"
            - name: COSO_DATABASE_RW_CONNECTION_MAX_IDLE
              value: "6"
            - name: COSO_DATABASE_RW_CONNECTION_TOTAL
              value: "12"
            - name: COSO_DATABASE_CONNECTION_TIMEOUT_SEC
              value: "20"
            - name: ITOM_CDF_EXTERNAL_SSL_CERTS_DIR
              value: /var/opt/OV/certs
            - name: LOG_PROPERTIES_LISTENER_ENABLED
              value: "true"
           {{- if (ne .Values.global.nom.edition "express") }}
           {{- if .Values.global.minio.isSelected }}
            - name: COSO_MINIO_HOST
              value: {{ .Values.global.externalAccessHost | quote }}
           {{- if (eq .Values.global.cluster.k8sProvider "azure") }}
            - name: COSO_MINIO_PORT
              value: {{ .Values.minio.port.azure | quote }}
           {{- else }}
            - name: COSO_MINIO_PORT
              value: {{ .Values.minio.port.default | quote }}
           {{- end }}
            - name: COSO_MINIO_ACCESS_KEY
              {{- include "helm-lib.injectVar" (dict "varName" "minio.accessKey" "Values" .Values "Template" .Template) | nindent 14 }}
            - name: COSO_MINIO_SECRET_KEY
              {{- include "helm-lib.injectVar" (dict "varName" "minio.secretKey" "Values" .Values "Template" .Template) | nindent 14 }}
           {{- end }}
           {{- if eq .Values.global.cluster.k8sProvider "aws" }}
            - name: COSO_S3_HOST
              {{- include "helm-lib.injectVar" (dict "varName" "aws.host" "Values" .Values "Template" .Template) | nindent 14 }}
            - name: COSO_S3_PORT
              value: {{ .Values.minio.port.s3 | quote }}
            - name: COSO_S3_ACCESS_KEY
              {{- include "helm-lib.injectVar" (dict "varName" "minio.accessKey" "Values" .Values "Template" .Template) | nindent 14 }}
            - name: COSO_S3_SECRET_KEY
              {{- include "helm-lib.injectVar" (dict "varName" "minio.secretKey" "Values" .Values "Template" .Template) | nindent 14 }}
            - name: COSO_S3_REGION
              {{- include "helm-lib.injectVar" (dict "varName" "aws.region" "Values" .Values "Template" .Template) | nindent 14 }}
            - name: COSO_CLUSTER_K8SPROVIDER
              value: {{ .Values.global.cluster.k8sProvider | quote }}
            {{- end }}
            {{- end }}
            {{- end }}
            - name: JVM_HEAP_MIN
              value: 512m
            - name: JVM_HEAP_MAX
              value: 2048m

            {{- if and ( .Values.global.perfTroubleshooting.isSelected) ( .Values.sybase.host) }}
            - name: SYBASEIQ_DATABASE_HOST
              value: {{ .Values.sybase.host | quote }}
            - name: SYBASEIQ_DATABASE_PORT
              value: {{ .Values.sybase.port | quote }}
            - name: SYBASEIQ_DATABASE_DB
              value: {{ .Values.sybase.db | quote }}
            - name: SYBASEIQ_DATABASE_USER
              value: {{ .Values.sybase.user | quote }}
            - name: SYBASEIQ_DATABASE_PASSWORD_KEY
              value: "SYBASE_DB_PASSWORD_KEY"
            - name: SYBASEIQ_DATABASE_CONNECTION_MIN_IDLE
              value: "10"
            - name: SYBASEIQ_DATABASE_CONNECTION_MAX_IDLE
              value: "10"
            - name: SYBASEIQ_DATABASE_CONNECTION_TOTAL
              value: "20"
            - name: SYBASEIQ_DATABASE_CONNECTION_TIMEOUT_SEC
              value: "20"
            {{- end }}
            - name: IDM_SVC_SERVICE_HOST
              value: {{ include "helm-lib.getInternalIdmHost" . | default  (printf "%s%s.%s" .Values.deployment.idm.namePrefix .Values.deployment.idm.service .Release.Namespace) }}
            - name: IDM_SVC_SERVICE_PORT
              value: {{ include "helm-lib.getInternalIdmPort" . | default .Values.deployment.idm.port | quote }}
            - name: NOM_IDM_ADMIN_USER
              value: {{ .Values.deployment.idm.user | quote }}
            - name: NOM_ADMIN_PASSWORD_KEY
              value: {{ .Values.deployment.idm.passwordKey | quote }}
          volumeMounts:
          - name: itom-coso-dl-data-access-log-vol
            mountPath: /var/opt/OV/log
            subPath: itom-coso-dl-data-access
          - name: itom-coso-dl-data-access-data-vol
            mountPath: /var/opt/OV
            subPath: itom-coso-dl-data-access
          {{- if .Values.global.database.tlsTruststore }}
          - name: certs-volume
            mountPath: /var/opt/OV/certs
          {{- else }}
          - name: itom-coso-dl-data-access-data-vol
            mountPath: /var/opt/OV/certs
            subPath: nom/certificates
          {{- end }}
          - name: vault-token
            mountPath: /var/run/secrets/boostport.com
          - name: temp
            mountPath: /tmp
        - name: kubernetes-vault-renew
          image: {{ .Values.global.docker.registry }}/{{ .Values.global.docker.orgName }}/{{ .Values.global.vaultRenew.image }}:{{ .Values.global.vaultRenew.imageTag }}
          imagePullPolicy: {{ .Values.global.docker.imagePullPolicy }}
          volumeMounts:
            - name: vault-token
              mountPath: /var/run/secrets/boostport.com
      restartPolicy: Always
      volumes:
      - name: itom-coso-dl-data-access-data-vol
        {{- include "helm-lib.pvcStorage" (dict "claim" "dataVolumeClaim" "Release" .Release "Template" .Template "Values" .Values ) | nindent 8 }}
      - name: itom-coso-dl-data-access-log-vol
        {{- include "helm-lib.pvcStorage" (dict "claim" "logVolumeClaim" "Release" .Release "Template" .Template "Values" .Values ) | nindent 8 }}
      {{- if .Values.global.database.tlsTruststore }}
      - name: certs-volume
        configMap:
          name: {{ .Values.global.database.tlsTruststore }}
      {{- end }}
      - name: vault-token
        emptyDir: {}
      - name: temp
        emptyDir: {}
{{- else }}
# we need to deploy SOMETHING in this file, to prevent errors during "helm delete" of empty file
apiVersion: v1
kind: ConfigMap
metadata:
  name: itom-coso-dl-data-access-cm
data:
  bvd.isSelected: {{ .Values.global.bvd.isSelected | quote }}
  coso.isSelected: {{ .Values.global.coso.isSelected | quote }}
  perfTroubleshooting.isSelected: {{ .Values.global.perfTroubleshooting.isSelected | quote }}
{{- end }}
