{{ if and (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1") .Values.global.prometheus.deployPrometheusConfig }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: itomdipulsar
    app.kubernetes.io/name: itomdipulsar-proxy
    {{- include "servicemonitor.labels" . | nindent 4 }}
  name: itomdipulsar-proxy
  namespace: {{ .Release.Namespace }}
spec:
  endpoints:
  - tlsConfig:
      serverName: itomdipulsar-proxy
      {{- include "servicemonitor.tlsConfig.certs.re" . | nindent 6 }}
    port: metrics
    path: /metrics
    scheme: https
    interval: 20s
    relabelings:
    {{- include "servicemonitor.relabelings" . | nindent 4 }}
    metricRelabelings:
    {{- include "servicemonitor.metricRelabelings" . | nindent 4 }}
  selector:
    matchLabels:
      app: itomdipulsar
      component: proxy
  {{- include "servicemonitor.namespaceSelector" . | nindent 2 }}
{{ end }}