global:
  docker:
    # set the global.docker.registry and orgName to your internal Docker registry/org
    registry: docker.io/v1
    orgName: hpeswitom
    imagePullSecret: ""
    imagePullPolicy: IfNotPresent

  # User ID and group ID to run as
  securityContext:
    user: "1999"
    fsGroup: "1999"

  rbac:
    # Specifies whether a ServiceAccount should be created
    serviceAccountCreate: true

  # REQUIRED: The externalAccessHost is the end-point for the service
  externalAccessHost: nomultimate.integraecom.com

  nginx:
    annotationPrefix:

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi


# Assigning pods to cluster nodes
nodeSelector:
  Worker: label
tolerations: []
affinity: {}


#####################
# Image definitions
#####################
nomWebServer:
  image: itom-nom-web-server
  imageTag: 1.0.55
