{{ if and (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1") .Values.global.prometheus.deployPrometheusConfig }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: itomdiminio
    app.kubernetes.io/name: itom-di-minio
    {{- include "servicemonitor.labels" . | nindent 4 }}
  name: itom-di-minio
  namespace: {{ .Release.Namespace }}
spec:
  endpoints:
  - tlsConfig:
      serverName: metrics.itom-di-minio-svc.{{ .Release.Namespace }}.svc.cluster.local
      {{- include "servicemonitor.tlsConfig.certs.re" . | nindent 6 }}
    port: metrics
    path: /minio/prometheus/metrics
    scheme: https
    interval: 20s
    relabelings:
    {{- include "servicemonitor.relabelings" . | nindent 4 }}
  selector:
    matchLabels:
      app: itomdiminio
  {{- include "servicemonitor.namespaceSelector" . | nindent 2 }}
{{ end }}