{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.app.name }}
spec:
  to:
    kind: Service
    name: {{ .Values.app.name }}
  port:
    targetPort: {{ .Values.app.port }}
  tls:
    termination: {{ .Values.route.tlsTermination }}
{{- end }}
