apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/name: itom-nom-zookeeper
    app.kubernetes.io/version: {{.Values.zookeeper.imageTag}}
  name: itom-nom-zookeeper
  annotations:
    deployment.microfocus.com/default-replica-count: "1"
    deployment.microfocus.com/runlevel: UP
spec:
  serviceName: nomzk
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      name: itom-nom-zookeeper
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: itom-nom-zookeeper
        app.kubernetes.io/version: {{.Values.zookeeper.imageTag}}
        name: itom-nom-zookeeper
    spec:
      serviceAccountName: itom-nom-zookeeper
      terminationGracePeriodSeconds: 30
      {{- if ne .Values.global.docker.imagePullSecret "" }}
      imagePullSecrets:
      - name: {{ .Values.global.docker.imagePullSecret }}
      {{- end }}
      containers:
      - name: itom-zookeeper
        imagePullPolicy: {{ .Values.global.docker.imagePullPolicy }}
        image: {{ .Values.global.docker.registry }}/{{ .Values.global.docker.orgName }}/{{ .Values.zookeeper.image }}:{{ .Values.zookeeper.imageTag }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        ports:
        - containerPort: 2181
          name: client
        - containerPort: 2888
          name: server
        - containerPort: 3888
          name: leader-election
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - 'CMD_OUT=`echo "ruok" | (exec 3<>/dev/tcp/127.0.0.1/2181; cat >&3; cat <&3; exec 3<&-)`; if [ "$CMD_OUT" != "imok" ]; then exit 1; fi'
          initialDelaySeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - 'CMD_OUT=`echo "ruok" | (exec 3<>/dev/tcp/127.0.0.1/2181; cat >&3; cat <&3; exec 3<&-)`; if [ "$CMD_OUT" != "imok" ]; then exit 1; fi'
          initialDelaySeconds: 10
          timeoutSeconds: 5
        env:
        - name: uid
          value: {{ .Values.global.securityContext.user | quote }}
        - name: guid
          value: {{ .Values.global.securityContext.fsGroup | quote }}
        - name : ZK_REPLICAS
          value: {{ .Values.deployment.replicas | quote }}
        - name : ZK_MIN_HEAP_SIZE
          valueFrom:
            configMapKeyRef:
                name: nomzk-cm
                key: jvm.min.heap
        - name : ZK_MAX_HEAP_SIZE
          valueFrom:
            configMapKeyRef:
                name: nomzk-cm
                key: jvm.max.heap
        - name : ZK_TICK_TIME
          valueFrom:
            configMapKeyRef:
                name: nomzk-cm
                key: tick
        - name : ZK_INIT_LIMIT
          valueFrom:
            configMapKeyRef:
                name: nomzk-cm
                key: init
        - name : ZK_SYNC_LIMIT
          valueFrom:
            configMapKeyRef:
                name: nomzk-cm
                key: tick
        - name : ZK_MAX_CLIENT_CNXNS
          valueFrom:
            configMapKeyRef:
                name: nomzk-cm
                key: client.cnxns
        - name: ZK_SNAP_RETAIN_COUNT
          valueFrom:
            configMapKeyRef:
                name: nomzk-cm
                key: snap.retain
        - name: ZK_PURGE_INTERVAL
          valueFrom:
            configMapKeyRef:
                name: nomzk-cm
                key: purge.interval
        - name: ZK_CLIENT_PORT
          value: "2181"
        - name: ZK_SERVER_PORT
          value: "2888"
        - name: ZK_ELECTION_PORT
          value: "3888"
        - name: ZK_USER_GROUP
          value: "nom"
        - name: ZK_LOG_TO_FILE
          value: "true"
        - name: ZK_LOG_LEVEL
          value: "INFO"
        - name: ZK_SNAPSHOT_TRUST_EMPTY
          value: "true"  
        - name: SERVICENAME
          value: {{ include "helm-lib.serviceName.zookeeper" (dict "Release" .Release "Values" .Values "Template" .Template ) }}
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          value: itom-nom-zookeeper
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CONTAINER_NAME
          value: itom-nom-zookeeper
        volumeMounts:
        - name: nom-zk-volume
          mountPath: /opt/zookeeper/data
          subPath: nom-zk/data
        - name: nom-zk-volume
          mountPath: /opt/zookeeper/datalog
          subPath: nom-zk/datalog
        - name: nom-zk-log-vol
          mountPath: /opt/zookeeper/log
          subPath: nom-zk/log
      volumes:
      - name: nom-zk-volume
        {{- include "helm-lib.pvcStorage" (dict "claim" "dataVolumeClaim" "Release" .Release "Template" .Template "Values" .Values ) | nindent 8 }}
      - name: nom-zk-log-vol
        {{- include "helm-lib.pvcStorage" (dict "claim" "logVolumeClaim" "Release" .Release "Template" .Template "Values" .Values ) | nindent 8 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
