apiVersion: v1
kind: Service
metadata:
  name: itom-nom-ui
  labels:
    name: itom-nom-ui
spec:
  ports:
    - port: 8443
      protocol: TCP
      name: itom-nom-ui-port
      targetPort: 8443
  selector:
    name: itom-nom-ui
