{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
apiVersion: networking.k8s.io/v1
{{ else if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1/Ingress" }}
apiVersion: networking.k8s.io/v1beta1
{{ else }}
apiVersion: extensions/v1beta1
{{ end -}}
kind: Ingress
metadata:
  name: nom-ingress-ui
  annotations:
    {{ default "ingress.kubernetes.io" .Values.global.nginx.annotationPrefix }}/secure-backends: "true"
    {{ default "ingress.kubernetes.io" .Values.global.nginx.annotationPrefix }}/backend-protocol: "HTTPS"
    {{ default "ingress.kubernetes.io" .Values.global.nginx.annotationPrefix }}/force-ssl-redirect: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: {{ .Values.global.externalAccessHost }} 
    http:
      paths:
      - path: /externalcomponents/nom/widgets
        {{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
        pathType: Prefix
        backend:
          service:
            name: itom-nom-ui
            port: 
              number: 8443
        {{- else }}      
        backend:
          serviceName: itom-nom-ui
          servicePort: 8443
        {{- end }}  
