{{- if .Values.global.rbac.pspEnabled }}
apiVersion: policy/v1beta1
kind: PodSecurityPolicy

metadata:
  name: itom-di-vertica-psp
  labels:
    helm.sh/chart: itom-di-vertica
    app.kubernetes.io/name: itom-di-vertica
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  allowPrivilegeEscalation: true
  allowedCapabilities:
  - SETUID
  - SETGID
  - SYS_ADMIN
  fsGroup:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - '*'
{{- end }}
