{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "minio.fullname" . }}-secret
  labels:
    app: {{ template "minio.name" . }}
    chart: {{ template "minio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  accesskey: {{ "AKIAIOSFODNN7EXAMPLE" | b64enc | quote }}
  secretkey: {{ "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY" | b64enc | quote }}
{{- if .Values.gcsgateway.enabled }}
  gcs_key.json: {{ .Values.gcsgateway.gcsKeyJson | b64enc }}
{{- end }}
{{- end }}
