{{- if .Values.global.rbac.serviceAccountCreate }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.deployment.rbac.serviceAccount | default "itom-di-minio-sa" }}
  labels:
    {{- include "minio.standardLabels" . | nindent 4 }}
  namespace: {{ .Release.Namespace | quote }}
imagePullSecrets:
- name: {{ .Values.global.docker.imagePullSecret | default "registrypullsecret" }}
{{- end -}}
