{{- if and (eq (include  "minio.is_cloud_deployment" . ) "false") (eq .Values.diminio.service.isNodePortEnabled true) (eq .Values.diminio.service.type "NodePort") }}
{{- if not .Values.diminio.ingress.enabled }}
{{- if eq .Values.mode "distributed" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "minio.fullname" . }}-nodeport
  labels:
    {{- include "minio.standardLabels" . | nindent 4 }}
  annotations:
    {{- include "minio.template.annotations" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - name: service
      port: {{ .Values.diminio.service.port }}
      protocol: TCP
      nodePort: {{ .Values.diminio.service.nodePort }}
  selector:
    app: {{ template "minio.name" . }}
{{- end }}
{{- end }}
{{- end }}
