{{ if and (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1") .Values.global.prometheus.deployPrometheusConfig }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: itomdipostload
    app.kubernetes.io/name: itom-di-taskexecutor
    {{- include "servicemonitor.labels" . | nindent 4 }}
  name: itom-di-taskexecutor
  namespace: {{ .Release.Namespace }}
spec:
  endpoints:
  - tlsConfig:
      serverName: itom-di-message-bus-svc
      {{- include "servicemonitor.tlsConfig.certs.rid" . | nindent 6 }}
    port: metrics
    path: /metrics
    scheme: https
    interval: 20s
    relabelings:
    {{- include "servicemonitor.relabelings" . | nindent 4 }}
  selector:
    matchLabels:
      app: itomdipostload
      app.kubernetes.io/name: itom-di-taskexecutor
  {{- include "servicemonitor.namespaceSelector" . | nindent 2 }}
{{ end }}