#
# This is the configuration for IDM.  The original source came from CDF "core" namespace, but
# now delivered with each NOM composition chart.
#

apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
  name: idm-conf-file
data:
  com.microfocus.cdf__2018.11__Add_Update_User.json: |
    {{- .Files.Get "idm/com.microfocus.cdf__2018.11__Add_Update_User.json" | nindent 4 }}

  com.microfocus.cdf__2019.02__Add_Update_User.json: |
    {{- .Files.Get "idm/com.microfocus.cdf__2019.02__Add_Update_User.json" | nindent 4 }}

  {{- if not .Values.global.containerizedMode }}
  system_resource_config__1.29.1.0__update.json: |
    {{- .Files.Get "idm/system_resource_config__1.29.1.0__update.json" | nindent 4 }}
  {{- end }}

