apiVersion: v1
kind: ConfigMap
metadata:
  name: default-ca-certificates
data:
  {{- if .Values.caCertificates }}
  {{- range $key, $val := .Values.caCertificates }}
  {{- if (contains "-----BEGIN CERTIFICATE-----" $val) }}
  {{- printf "%s: |" $key | nindent 2}}
  {{- $newVal := ( replace " " "\n" $val | replace "\nCERTIFICATE" " CERTIFICATE" ) }}
  {{- printf "%s" $newVal | nindent 4}}
  {{- else }}
  {{- printf "%s: |" $key | nindent 2}}
  {{- printf "%s" (b64dec $val) | nindent 4}}
  {{- end }}
  {{- end }}
  {{- end }}
