apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: microfocus:itom:nom:update-k8s-secret
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - update