apiVersion: v1
kind: ConfigMap
metadata:
  name: secret-storage
  labels:
    name: secret-storage
data:
  TYPE: {{ default "k8s" .Values.global.secretStorage | quote }}
  SECRET_STORAGE_NAME: {{ default "nom-secret" .Values.global.secretStorageName | quote }}
