{{- if .Values.global.rbac.serviceAccountCreate }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.deployment.rbac.serviceAccount | default "itom-di-postload-sa" }}
  namespace: {{ .Release.Namespace }}
imagePullSecrets:
- name: {{ .Values.global.docker.imagePullSecret | default "registrypullsecret" }}
{{- end }}
---
{{- if .Values.global.rbac.roleCreate }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "itomdi:postload"
rules:
- apiGroups: [""]
  resources:  
   - configmaps
   - serviceaccounts
   - pods  
   - services
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:   
   - secrets
  verbs: ["list", "watch", "get", "patch"]   
- apiGroups: ["apps"]
  resources:
   - deployments    
   - replicasets
  verbs: ["get", "list", "watch"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "itomdi:postload"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "itomdi:postload"
subjects:
- kind: ServiceAccount  
  name: {{ .Values.deployment.rbac.serviceAccount | default "itom-di-postload-sa" }}  
  namespace: {{ .Release.Namespace }}
{{- end }}
