apiVersion: v1
kind: Service
metadata:
  labels:
    app: itomdipostload
    app.kubernetes.io/name: itom-di-taskcontroller
    app.kubernetes.io/managed-by: {{.Release.Name}}
    app.kubernetes.io/version: {{.Values.postload.taskGenerator.imageTag}}
    itom.microfocus.com/capability: itom-data-ingestion
    tier.itom.microfocus.com/backend: backend
  name: itom-di-taskcontroller-svc
spec:
  ports:
    - name: taskcontroller-port
      port: 8443
      protocol: TCP
      targetPort: 8443
    - name: metrics
      port: 5555
      protocol: TCP
      targetPort: 8443
  selector:
    app: itom-di-postload-taskcontroller