{{- if and .Values.diadmin.config.isNodePortEnabled (eq (include  "admin.is_cloud_deployment" . ) "false") }}
kind: Service
apiVersion: v1
metadata:
  name: itom-di-administration-nodeport
spec:
  type: NodePort
  ports:
    - port: 18443
      protocol: TCP
      name: itom-di-administration-nodeport
      targetPort: 8443
      nodePort: {{.Values.diadmin.config.adminNodePort}}
  selector:
    app: itom-di-administration
{{end}}