apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: itom-di-administration-svc
    app.kubernetes.io/managed-by: {{.Release.Name}}
    app.kubernetes.io/version: {{.Values.admin.imageTag}}
    itom.microfocus.com/capability: itom-data-ingestion
    tier.itom.microfocus.com/backend: backend
  name: itom-di-administration-svc
  annotations:
    {{ template "admin.service_domain" . }}
    {{- if eq .Values.global.cluster.k8sProvider "aws" }}
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    {{- else if eq .Values.global.cluster.k8sProvider "azure" }}
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    {{- end }}
spec:
  type: {{ template "admin.service_type" . }}
  {{ template "admin.azure_loadbalancer_ip" . }}
  {{ template "admin.cloud_loadbalancer_source_range" . }}
  ports:
  {{- if (eq (include  "admin.is_cloud_deployment" . ) "false") }}
  - name: administration-port-old
    port: 8443
    protocol: TCP
    targetPort: 8443
  {{- end }}
  - name: administration-port
    port: 18443
    protocol: TCP
    targetPort: 8443
  selector:
    app: itom-di-administration