# You must accept the Micro Focus EULA to deploy NOM Ultimate.
# The EULA can be found at: https://www.microfocus.com/en-us/legal/software-licensing
acceptEula: true

persistence:
  # NOM creates 4 or 5 PVCs using the defaultStorageClass.  This is one mechanism
  # for changing the storageClass, the other is global.persistence.storageClasses.*
  # found below.
  defaultStorageClass: do-block-storage

global:
  nom:
    edition: ultimate    # DO NOT CHANGE

    # Deployment size is used to scale resources.  Acceptable values: demo, small
    # medium, large.  Default is (currently) small.
    deploySize: large

    # Used internally to enable additional debugging capabilities if service
    # charts are modified to take advantage of the same.
    debug:
      jmxConsole: false          # DO NOT CHANGE: Intended for INTERNAL USE ONLY
      logLevel: INFO             # DO NOT CHANGE: Intended for INTERNAL USE ONLY

  prometheus:
    # Setting deployPrometheusConfig & deployGrafanaConfig to true would enable the self-monitoring content for NOM & OPTIC DL pods
    # If deployPrometheusConfig is true, CDF Monitoring Framework is assumed to be installed and will use it for metric storage
    deployPrometheusConfig: false
    deployGrafanaConfig: false

  docker:
    # set the global.docker.registry and orgName to your internal Docker registry/org
    registry: docker.io/v1
    orgName: hpeswitom
    imagePullSecret: ""
    imagePullPolicy: IfNotPresent

  #Service chart should inject the FQDN into ingress.spec.rules[].host depending upon the parameter “.global.setFqdnInIngress”.
  setFqdnInIngress: true

  # Define persistent storage:
  #    dataVolumeClaim is a persistent volume claim (PVC) for storing data files.
  #    dbVolumeClaim is a PVC for storing database files.
  #    configVolumeClaim is a PVC for storing configuration files.
  #    logVolumeClaim is a PVC for storing log files.
  #    monitoringVolumeClaim is a PVC for storing log files (if cosoMonitoring=true)
  #
  # If any of these is undefined, then:
  #    If "persistence.enabled" is set to "true" then the specified PVCs will be
  #    automatically created when the chart is deployed.  But this requires that there
  #    are available PVs to bind to.
  #
  #    If "persistence.enabled" is false, and "isDemo" is set to true, then temporary ephemeral
  #    storage will be created.  Otherwise, the chart will fail to deploy because you must
  #    "opt in" to temporary storage.
  #
  isDemo: false                 # set to "true" to opt in to ephemeral storage
  localPersistence:
    enabled: true              # set to "true" to enable local PVC creation (worker nodes must have local storage)
  persistence:
    enabled: true              # set to "true" to enable auto-PVC creation (requires available PVs)
    dataVolumeClaim: data-idm
    dbVolumeClaim: db-idm
    configVolumeClaim: config-idm
    logVolumeClaim: log-idm

    # Specify the size of each of the PVCs
    configVolumeSize: 1Gi
    dataVolumeSize: 1Gi
    dbVolumeSize: 1Gi
    logVolumeSize: 1Gi

    # Used to inject storageClasses into PVC creation.  All values should be blank by default, and
    # customer can change any/all to match the actual storageClasses used in their environment.
    storageClasses:
      # All 4-5 NOM PVCs are created using "default-rwx", and COSO uses "default-rwo" for
      # MinIO and "fast-rwo" for LVP.
      default-rwx:
      default-rwo:
      fast-rwx:
      fast-rwo:

  # The user/group IDs (UID/GID) for runtime deployment, and ownership of persistent storage.
  securityContext:
    user: "1999"
    fsGroup: "1999"

  # values for shared OPTIC Reporting
  services:
    optic: false                 # temporarily need this one AND the one below
    sharedOpticReporting: false
    namespace:
    namePrefix:
    external:
      host:
      port: 80
    internal:
      host:
      port: 80
    diAdminPort:
    diDataAccessPort:
    diPulsarProxyClientPort:
    diPulsarProxyWebPort:


  # DO NOT CHANGE: This is the Kubernetes secret created by the "generate_secrets" script.
  initSecrets: nom-secret

  # DO NOT CHANGE: Switches to use k8s instead of vault to store secrets in nom-secret
  secretStorage: k8s
  secretStorageName: nom-secret

  # DO NOT CHANGE: The nginx service needs a default HTTP Backend service
  nginx:
    defaultBackendService: itom-nom-default-http-backend
    annotationPrefix: ingress.kubernetes.io

  # DO NOT CHANGE: The global config map for this composition chart
  configMap: nom-ultimate-cm

  # Global image references:
  vaultRenew:
    image: kubernetes-vault-renew
    imageTag: 0.15.0-0038
  vaultInit:
    image: kubernetes-vault-init
    imageTag: 0.15.0-0038
  waitForIt:
    image: itom-waitforit
    imageTag: 01.00.006
  busybox:
    image: itom-busybox
    imageTag: 1.38.0-009
  opensuse:
    image: opensuse-base
    imageTag: 15.3-0032



  # By default, the BVD chart will be deployed, but it can be de-selected
  bvd:
    isSelected: true

  # By default, the COSO chart will be deployed, but it can be de-selected
  coso:
    isSelected: true

  # This is for COSO monitoring feature
  cosoMonitoring:
    isSelected: true

  perfTroubleshooting:
    isSelected: true

  # This is for NNMI, NA, Traffic, QA flags
  traffic:
    isSelected: true
  qa:
    isSelected: true

  # This is for Multicast SPI feature
  multicast:
    isSelected: false
  mpls:
    isSelected: false
  ipt:
    isSelected: false

  # This flag is added for aws deployment. Default value cdf set for on-perm
  cluster:
    k8sProvider: cdf

  # By default, UI workflow pages will not be available
  isEpr: false

  #
  # Specify the database details for Postgres.  By default embedded Postgres
  # container is deployed.
  #
  # DO NOT CHANGE: this is how certificates are injected for external Postgres
  tlsTruststore: default-ca-certificates  # should match below
  database:
    # DO NOT CHANGE: this is how certificates are injected for external Postgres
    tlsTruststore: default-ca-certificates

    internal: false              # if false, then use external (Postgres) DB
    host: silo12-master.postgresql.bdh.integraecom.com
    port: 5432 # specify database server port number
    user: nnm_admin
    #userPasswordKey

    # Note NOM 2020.05 does not support "createDb=true" feature at this time
    createDb: false             # if true, then "admin" and "adminPasswordKey" are required to create DBs
    #admin:
    #adminPasswordKey:

    # tlsEnabled=true requires certificates for external Postgres
    tlsEnabled: false

  apiClient:
    # DO NOT CHANGE: this is used to inject certificates for Pulsar client authentication
    authorizedClientCAs: api-client-ca-certificates

  #
  # In NOM "containerized Mode", the NNMi and NA services will be deployed as containers
  # in the cluster.  This is not yet supported in this edition  of NOM.
  # However for a "Mixed Mode" deployment (global.containerizedMode=false), you must specify
  # the external server details for NNMi and NA.
  #
  containerizedMode: false           # "true" is not supported

  #
  # In NOM Ultimate 2019.11, all services (NNMi, NA, Traffic, QoS) are external services.
  # Hence, you must specify the external server details for NNMi and NA.
  #
  nnmi:
    isSelected: true
    host: pxl0nnmi0011.integraecom.com
    failoverHost:  pxl0nnmi0009.integraecom.com
    port: 443
    user: system               # DO NOT CHANGE

  na:
    isSelected: true
    host: na.integraecom.com
    port: 443

  idm:
    #IDM configuration required for overriding default values set for oo deployment.
    idmTransportPasswordKey: idm_transport_admin_password
    signingKeySecretName: IDM_SIGNING_KEY
    adminUserKey: idm_admin_admin_password      # DO NOT CHANGE

  # DO NOT CHANGE: Required for COSO
  messageBus: pulsar

  ##################### Start Vertica Configuration #####################
  #
  # Change the following to enter external Vertica details.
  #
  vertica:
    embedded: false  # set to "true" (POC only) or define all of the following details
    host: pxl0nnmi0022.integraecom.com             # for external Vertica, change to <FQDN_OF_VERTICA>
    port: 5443                            # for external Vertica, change to <PORT_OF_VERTICA>
    db: verticadb                            # for external Vertica, change to <NAME_OF_DB>
    rwuser: vertica_rwuser                       # for external Vertica, change to <VERTICA_READ_WRITE_USER>
    rouser: vertica_rouser                       # for external Vertica, change to <VERTICA_READ_ONLY_USER>
    rwuserkey: ITOMDI_DBA_PASSWORD_KEY             # DO NOT CHANGE
    rouserkey: ITOMDI_ROUSER_PASSWORD_KEY          # DO NOT CHANGE
    tlsEnabled: false  # set to false if TLS is not enabled

  minio:
    isSelected: true
    clientAccessKey: ITOMDI_MINIO_CLIENT_ACCESS_KEY
    clientSecretKey: ITOMDI_MINIO_CLIENT_SECRET_KEY

  # DO NOT REMOVE Chart deployment fails if the di.tenant and di.deployment are not set explicitly
  di:
    tenant: provider
    deployment: default

  # Feature toggles, flags used to control certian experimental features in ui-foundation
  featureToggles: {"DISCARD_CHANGES_DIALOG": true }

  # Experimental
  telemetry:
    isSelected: false


# DO NOT CHANGE: Required to support k8s secrets for DI Monitoring
itomdimonitoring:
  monitoring:
    isBase64Encoded: true

# Tune the performance of itom-nom-metric-transformation pod using the below configurations.
nommetricstransform:
  deployment:
    database:
      dbName: btcd                              # OK to change for EXTERNAL Postgres
      user: user_btcd                                # OK to change for EXTERNAL Postgres
      userPasswordKey: BTCD_DB_PASSWD_KEY       # DO NOT CHANGE
# This is to control remapping of COSO administration and data access
# service ports
nomapiserver:
  coso:
    diAdminSvc:
      host: itom-di-administration-svc
      port: 18443
    diDataAccessSvc:
      host: itom-di-data-access-svc
      port: 28443

nomreportingcontent:
  coso:
    diAdminSvc:
      port: 18443

# The memory and disk space limits set for itomdipulsar and itomdidp are defaults for 5K nodes.
itomdipulsar:
  components:
    pulsar_manager: false     # DO NOT CHANGE, we do not want to deploy pulsar-manager
  bookkeeper:
    volumes:
      journal:
        size: "1Gi"
      ledgers:
        size: "6Gi"
  zookeeper:
    volumes:
      data:
        size: "1Gi"

itomdiminio:
  persistence:
    size: "1Gi"

##################### End Vertica Configuration #####################


bvd:
  params:
    suite:
      logo: "data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPHN2ZyB3aWR0aD0iNTZweCIgaGVpZ2h0PSI1NnB4IiB2aWV3Qm94PSIwIDAgNTYgNTYiIHZlcnNpb249IjEuMSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWxuczp4bGluaz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94bGluayI+CiAgICA8IS0tIEdlbmVyYXRvcjogU2tldGNoIDU3LjEgKDgzMDg4KSAtIGh0dHBzOi8vc2tldGNoLmNvbSAtLT4KICAgIDx0aXRsZT5BcnRib2FyZDwvdGl0bGU+CiAgICA8ZGVzYz5DcmVhdGVkIHdpdGggU2tldGNoLjwvZGVzYz4KICAgIDxnIGlkPSJBcnRib2FyZCIgc3Ryb2tlPSJub25lIiBzdHJva2Utd2lkdGg9IjEiIGZpbGw9Im5vbmUiIGZpbGwtcnVsZT0iZXZlbm9kZCI+CiAgICAgICAgPHBhdGggZD0iTTE4LjQ2NiwzNS4zNTIgTDE1LjQ3NiwzNS4zNTIgTDkuNTY1LDI3LjA5NSBMOS41NjUsMzUuMzUyIEw2LDM1LjM1MiBMNiwyMS4yMyBMOS40NSwyMS4yMyBMMTQuOTAxLDI5LjAwNCBMMTQuOTAxLDIxLjIzIEwxOC40NjYsMjEuMjMgTDE4LjQ2NiwzNS4zNTIgWiBNMzMuODMsMjguMjkxIEMzMy44MywyOS4zNDkwMDUzIDMzLjY2MTMzNSwzMC4zMjI2NjIyIDMzLjMyNCwzMS4yMTIgQzMyLjk4NjY2NSwzMi4xMDEzMzc4IDMyLjUxMTMzNjQsMzIuODY3OTk2OCAzMS44OTgsMzMuNTEyIEMzMS4yODQ2NjM2LDM0LjE1NjAwMzIgMzAuNTU2MzM3NiwzNC42NjE5OTgyIDI5LjcxMywzNS4wMyBDMjguODY5NjYyNCwzNS4zOTgwMDE4IDI3LjkzNDMzODUsMzUuNTgyIDI2LjkwNywzNS41ODIgQzI1Ljg5NDk5NDksMzUuNTgyIDI0Ljk2NzMzNzUsMzUuMzk4MDAxOCAyNC4xMjQsMzUuMDMgQzIzLjI4MDY2MjQsMzQuNjYxOTk4MiAyMi41NTYxNjk3LDM0LjE1NjAwMzIgMjEuOTUwNSwzMy41MTIgQzIxLjM0NDgzMDMsMzIuODY3OTk2OCAyMC44NzMzMzUsMzIuMTAxMzM3OCAyMC41MzYsMzEuMjEyIEMyMC4xOTg2NjUsMzAuMzIyNjYyMiAyMC4wMywyOS4zNDkwMDUzIDIwLjAzLDI4LjI5MSBDMjAuMDMsMjcuMjMyOTk0NyAyMC4xOTg2NjUsMjYuMjU5MzM3OCAyMC41MzYsMjUuMzcgQzIwLjg3MzMzNSwyNC40ODA2NjIyIDIxLjM0NDgzMDMsMjMuNzEwMTY5OSAyMS45NTA1LDIzLjA1ODUgQzIyLjU1NjE2OTcsMjIuNDA2ODMwMSAyMy4yODA2NjI0LDIxLjkwMDgzNTEgMjQuMTI0LDIxLjU0MDUgQzI0Ljk2NzMzNzUsMjEuMTgwMTY0OSAyNS44OTQ5OTQ5LDIxIDI2LjkwNywyMSBDMjcuOTM0MzM4NSwyMSAyOC44Njk2NjI0LDIxLjE4MDE2NDkgMjkuNzEzLDIxLjU0MDUgQzMwLjU1NjMzNzYsMjEuOTAwODM1MSAzMS4yODQ2NjM2LDIyLjQwNjgzMDEgMzEuODk4LDIzLjA1ODUgQzMyLjUxMTMzNjQsMjMuNzEwMTY5OSAzMi45ODY2NjUsMjQuNDgwNjYyMiAzMy4zMjQsMjUuMzcgQzMzLjY2MTMzNSwyNi4yNTkzMzc4IDMzLjgzLDI3LjIzMjk5NDcgMzMuODMsMjguMjkxIFogTTMwLjEwNCwyOC4yOTEgQzMwLjEwNCwyNy4wNjQzMjcyIDI5LjgxMjY2OTYsMjYuMDgzMDAzNyAyOS4yMywyNS4zNDcgQzI4LjY0NzMzMDQsMjQuNjEwOTk2MyAyNy44NzMwMDQ4LDI0LjI0MyAyNi45MDcsMjQuMjQzIEMyNS45NDA5OTUyLDI0LjI0MyAyNS4xNzQzMzYyLDI0LjYxMDk5NjMgMjQuNjA3LDI1LjM0NyBDMjQuMDM5NjYzOCwyNi4wODMwMDM3IDIzLjc1NiwyNy4wNjQzMjcyIDIzLjc1NiwyOC4yOTEgQzIzLjc1NiwyOS41MTc2NzI4IDI0LjAzOTY2MzgsMzAuNDk4OTk2MyAyNC42MDcsMzEuMjM1IEMyNS4xNzQzMzYyLDMxLjk3MTAwMzcgMjUuOTQwOTk1MiwzMi4zMzkgMjYuOTA3LDMyLjMzOSBDMjcuODczMDA0OCwzMi4zMzkgMjguNjQ3MzMwNCwzMS45NzEwMDM3IDI5LjIzLDMxLjIzNSBDMjkuODEyNjY5NiwzMC40OTg5OTYzIDMwLjEwNCwyOS41MTc2NzI4IDMwLjEwNCwyOC4yOTEgWiBNNDIuNjE2LDMyLjMxNiBMMzguOTgyLDI3LjI1NiBMMzguOTgyLDM1LjM1MiBMMzUuMzcxLDM1LjM1MiBMMzUuMzcxLDIxLjIzIEwzOC43OTgsMjEuMjMgTDQyLjY2MiwyNi45OCBMNDYuNTQ5LDIxLjIzIEw0OS45NTMsMjEuMjMgTDQ5Ljk1MywzNS4zNTIgTDQ2LjMxOSwzNS4zNTIgTDQ2LjMxOSwyNy4yNTYgTDQyLjcwOCwzMi4zMTYgTDQyLjYxNiwzMi4zMTYgWiIgaWQ9Ik5PTSIgZmlsbD0iI0ZGRkZGRiIgZmlsbC1ydWxlPSJub256ZXJvIj48L3BhdGg+CiAgICA8L2c+Cjwvc3ZnPg=="
      favicon: "/externalcomponents/nom/widgets/assets/favicon.ico"
      injectAllowNewEditPage: true      # enables the injection of a value, for the following parameter
      allowNewEditPage: false
      logo_large: "/externalcomponents/nom/widgets/assets/nomlogo.svg"
      name: Network Operations Management
      release: "2021.11"
      showPrintTool: true
    timeFormat: 24                    # By default, time format will be 24 hours

  deployment:
    database:
      dbName: bvd                               # OK to change for EXTERNAL Postgres
      user: bvd                                 # OK to change for EXTERNAL Postgres
      userPasswordKey: BVD_DB_PASSWD_KEY        # DO NOT CHANGE

oocentral:
  deployment:
    database:
      dbaPassSecret: POSTGRES_DB_PASSWORD

oodesigner:
  deployment:
    database:
      dbaPassSecret: POSTGRES_DB_PASSWORD


# DO NOT CHANGE: these parameters are required the internal Postgres database
postgres:
  deployment:
    suiteInitScripts: nom-database-init
  postgres:
    users: apls:APLS_DB_PASSWD_KEY&bvd:BVD_DB_PASSWD_KEY&idm:IDM_DB_PASSWD_KEY&btcd:BTCD_DB_PASSWD_KEY
    tlsEnabled: false

# Note that the following datbase user/dbName entries should not be changed for
# embedded Postgres database.
# But it is OK to change for external Postgres database.
autopass:
  deployment:
    idm:
      enableRbac: true                          # DO NOT CHANGE, required for AutoPass RBAC
    database:
      dbName: autopass_db                              # OK to change for EXTERNAL Postgres
      user: user_autopass_db                                # OK to change for EXTERNAL Postgres
      userPasswordKey: APLS_DB_PASSWD_KEY       # DO NOT CHANGE

idm:
  deployment:
    database:
      dbName: idm # OK to change for EXTERNAL Postgres
      user: user_idm_db # OK to change for EXTERNAL Postgres
      userPasswordKey: IDM_DB_PASSWD_KEY        # DO NOT CHANGE

itom-ingress-controller:
  backwardsCompatServiceName: false             # DO NOT CHANGE
  global:
    externalAccessPort: 80

