apiVersion: v1
kind: ServiceAccount
metadata: 
  name: "{{ template "monitoring.fullname" . }}-{{ .Values.monitoring.gencerts.component }}-sa"
  namespace: {{ .Release.Namespace }}
imagePullSecrets:
  - name: {{ .Values.global.docker.imagePullSecret | default "registrypullsecret" }}
---
# Role with required permissions for creating/updating Prometheus scrape certs
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "{{ template "monitoring.fullname" . }}-{{ .Values.monitoring.gencerts.component }}-role"
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - update
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ template "monitoring.fullname" . }}-{{ .Values.monitoring.gencerts.component }}-rb"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "{{ template "monitoring.fullname" . }}-{{ .Values.monitoring.gencerts.component }}-role"
subjects:
- kind: ServiceAccount
  name: {{ template "monitoring.fullname" . }}-{{ .Values.monitoring.gencerts.component }}-sa
  namespace: {{ .Release.Namespace }}
---
# Role with required permissions for vault-init, vault-renew containers
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "{{ template "monitoring.fullname" . }}-{{ .Values.monitoring.gencerts.component }}-vault-role"
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - list
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
    verbs:
      - get      
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ template "monitoring.fullname" . }}-{{ .Values.monitoring.gencerts.component }}-vault-rb"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "{{ template "monitoring.fullname" . }}-{{ .Values.monitoring.gencerts.component }}-vault-role"
subjects:
- kind: ServiceAccount
  name: {{ template "monitoring.fullname" . }}-{{ .Values.monitoring.gencerts.component }}-sa
  namespace: {{ .Release.Namespace }}