{{ if and (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1") .Values.global.prometheus.deployPrometheusConfig }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    {{- include "monitoring.vpename" . | nindent 4 }}
    {{- include "monitoring.standardLabels" . | nindent 4 }}
    {{- toYaml .Values.global.prometheus.prometheusSelector | nindent 4 }}
  name: "{{ template "monitoring.fullname" . }}-{{ .Values.monitoring.verticapromexporter.component }}"
  namespace: {{ .Release.Namespace }}
spec:
  endpoints:
  - tlsConfig:
      serverName: "{{ template "monitoring.fullname" . }}-{{ .Values.monitoring.verticapromexporter.component }}"
      {{- include "servicemonitor.tlsConfig.certs.rid" . | nindent 6 }}
    port: metrics
    path: /metrics
    scheme: https
    interval: {{ .Values.monitoring.verticapromexporter.config.scrapeIntervalSec }}s
    scrapeTimeout: {{ .Values.monitoring.verticapromexporter.config.scrapeIntervalSec }}s
    relabelings:
    {{- include "servicemonitor.relabelings" . | nindent 4 }}
  selector:
    matchLabels:
      {{- include "monitoring.vpename" . | nindent 6 }}
  {{- include "servicemonitor.namespaceSelector" . | nindent 2 }}
{{ end }}