{
 "title": "Telemetry",
 "description": "NOM Telemetry Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Switch",
    "label": "Switch",
    "query": {
     "query": "label_values(collector_bytes_count, RA)"
    }
   },
   {
    "name": "Collector",
    "label": "Collector",
    "query": {
     "query": "label_values(collector_bytes_count, LA)"
    }
   }
  ]
 },
 "panels": [
  { "title": "By Switch", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Bytes GRPCS Messages by Switch",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(collector_messages_total{PR=\"GRPCS\", RA=\"$Switch\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Bytes GRPC Messages by Switch",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(collector_messages_total{PR=\"GRPC\",RA=\"$Switch\"}[$__rate_interval])"
    }
   ]
  },
  { "title": "By Collector", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Stream Count to Collector",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "collector_streams_cnt" }
   ]
  },
  {
   "title": "Collector Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",pod=~\"^nom-telemetry-collector-.*\"}) by (pod)"
    }
   ]
  }
 ]
}