apiVersion: v1
kind: Service
metadata:
  name: itom-nom-api-server
  labels:
    name: itom-nom-api-server
spec:
  ports:
    - port: 8443
      protocol: TCP
      name: api-server-https
      targetPort: 8443
  selector:
    name: itom-nom-api-server
