{{ $namePrefix := default "itom" .Values.namePrefix }}
{{- if .Values.global.rbac.serviceAccountCreate}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: itom-nom-zookeeper
  namespace: {{ .Release.Namespace }}
imagePullSecrets:
  - name: {{ .Values.global.docker.imagePullSecret | default "registrypullsecret" }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: itom-nom-zookeeper:itom-vault-client
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: microfocus:cdf:{{ $namePrefix }}-vault-client
subjects:
  - kind: ServiceAccount
    name: itom-nom-zookeeper
    namespace: {{ .Release.Namespace }}
{{- end }}
